// Box content items for each product category
// Each item has: name, brand, price, drop chance (%), rarity, and image

export interface BoxItem {
  name: string
  brand: string
  price: number
  chance: number
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary"
  image: string
}

// Generic box content generator based on category
export function getBoxContentForCategory(category: string): BoxItem[] {
  const contentByCategory: Record<string, BoxItem[]> = {
    games: [
      {
        name: "PlayStation 5",
        brand: "Sony",
        price: 499.99,
        chance: 0.001,
        rarity: "legendary",
        image: "/playstation-5-console-white.jpg",
      },
      {
        name: "Xbox Series X",
        brand: "Microsoft",
        price: 449.99,
        chance: 0.002,
        rarity: "legendary",
        image: "/xbox-series-x-console-black.jpg",
      },
      {
        name: "Nintendo Switch OLED",
        brand: "Nintendo",
        price: 349.99,
        chance: 0.005,
        rarity: "epic",
        image: "/nintendo-switch-oled-white.jpg",
      },
      {
        name: "RTX 4070 GPU",
        brand: "NVIDIA",
        price: 599.99,
        chance: 0.001,
        rarity: "legendary",
        image: "/nvidia-rtx-4070-graphics-card.jpg",
      },
      {
        name: "DualSense Controller",
        brand: "Sony",
        price: 69.99,
        chance: 0.02,
        rarity: "rare",
        image: "/ps5-dualsense-controller-white.jpg",
      },
      {
        name: "Xbox Elite Controller",
        brand: "Microsoft",
        price: 179.99,
        chance: 0.01,
        rarity: "epic",
        image: "/xbox-elite-controller-series-2.jpg",
      },
      {
        name: "Razer Kraken Headset",
        brand: "Razer",
        price: 79.99,
        chance: 0.03,
        rarity: "rare",
        image: "/razer-kraken-gaming-headset-green.jpg",
      },
      {
        name: "Logitech G Pro X",
        brand: "Logitech",
        price: 129.99,
        chance: 0.02,
        rarity: "rare",
        image: "/logitech-g-pro-x-keyboard-rgb.jpg",
      },
      {
        name: "SteelSeries Arctis 7",
        brand: "SteelSeries",
        price: 149.99,
        chance: 0.02,
        rarity: "rare",
        image: "/steelseries-arctis-7-wireless-headset.jpg",
      },
      {
        name: "HyperX Cloud II",
        brand: "HyperX",
        price: 99.99,
        chance: 0.03,
        rarity: "uncommon",
        image: "/hyperx-cloud-2-gaming-headset-red.jpg",
      },
      {
        name: "Corsair K70 RGB",
        brand: "Corsair",
        price: 169.99,
        chance: 0.02,
        rarity: "rare",
        image: "/corsair-k70-rgb-mechanical-keyboard.jpg",
      },
      {
        name: "Razer DeathAdder V3",
        brand: "Razer",
        price: 89.99,
        chance: 0.03,
        rarity: "uncommon",
        image: "/razer-deathadder-v3-gaming-mouse.jpg",
      },
      {
        name: "Steam Gift Card €50",
        brand: "Steam",
        price: 50.0,
        chance: 0.05,
        rarity: "uncommon",
        image: "/steam-gift-card-50-euro.jpg",
      },
      {
        name: "PlayStation Plus 12M",
        brand: "Sony",
        price: 59.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/playstation-plus-card-12-months.jpg",
      },
      {
        name: "Game Pass Ultimate 3M",
        brand: "Microsoft",
        price: 44.99,
        chance: 0.05,
        rarity: "uncommon",
        image: "/xbox-game-pass-ultimate-card.jpg",
      },
      {
        name: "RGB Mouse Pad XXL",
        brand: "Generic",
        price: 29.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Controller Stand",
        brand: "Generic",
        price: 19.99,
        chance: 0.1,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Gaming Stickers Pack",
        brand: "Generic",
        price: 9.99,
        chance: 0.15,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    "card-games": [
      {
        name: "Charizard VMAX",
        brand: "Pokemon",
        price: 450.0,
        chance: 0.001,
        rarity: "legendary",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Blue-Eyes White Dragon",
        brand: "Yu-Gi-Oh",
        price: 299.99,
        chance: 0.002,
        rarity: "legendary",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Black Lotus",
        brand: "MTG",
        price: 999.99,
        chance: 0.0001,
        rarity: "legendary",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Pikachu VMAX",
        brand: "Pokemon",
        price: 189.99,
        chance: 0.005,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Dark Magician",
        brand: "Yu-Gi-Oh",
        price: 79.99,
        chance: 0.01,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Booster Box Pokemon",
        brand: "Pokemon",
        price: 149.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Yu-Gi-Oh Tin Box",
        brand: "Yu-Gi-Oh",
        price: 24.99,
        chance: 0.05,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "MTG Draft Booster",
        brand: "MTG",
        price: 39.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Pokemon ETB",
        brand: "Pokemon",
        price: 49.99,
        chance: 0.03,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Card Sleeves Premium",
        brand: "Ultra Pro",
        price: 12.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Deck Box",
        brand: "Ultra Pro",
        price: 9.99,
        chance: 0.1,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Playmat",
        brand: "Generic",
        price: 19.99,
        chance: 0.06,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    tv: [
      {
        name: 'LG OLED 55"',
        brand: "LG",
        price: 1299.99,
        chance: 0.001,
        rarity: "legendary",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: 'Samsung 65" QLED',
        brand: "Samsung",
        price: 999.99,
        chance: 0.002,
        rarity: "legendary",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Apple TV 4K",
        brand: "Apple",
        price: 179.99,
        chance: 0.01,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Chromecast 4K",
        brand: "Google",
        price: 69.99,
        chance: 0.03,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Fire TV Stick 4K",
        brand: "Amazon",
        price: 49.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Netflix Gift Card €50",
        brand: "Netflix",
        price: 50.0,
        chance: 0.05,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Anime Figure",
        brand: "Bandai",
        price: 89.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Funko Pop Marvel",
        brand: "Funko",
        price: 14.99,
        chance: 0.06,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Movie Poster Signed",
        brand: "Generic",
        price: 149.99,
        chance: 0.01,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Streaming Snack Box",
        brand: "Generic",
        price: 29.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    sport: [
      {
        name: "Nike Air Jordan 1",
        brand: "Nike",
        price: 179.99,
        chance: 0.005,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Adidas Predator",
        brand: "Adidas",
        price: 249.99,
        chance: 0.003,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Official Match Ball",
        brand: "Nike",
        price: 149.99,
        chance: 0.01,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "NBA Jersey Authentic",
        brand: "Nike",
        price: 119.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Fitbit Charge 5",
        brand: "Fitbit",
        price: 149.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Protein Powder 2kg",
        brand: "Optimum",
        price: 59.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Resistance Bands Set",
        brand: "Generic",
        price: 29.99,
        chance: 0.06,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Shaker Bottle",
        brand: "BlenderBottle",
        price: 14.99,
        chance: 0.1,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Sports Towel",
        brand: "Nike",
        price: 19.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Water Bottle 1L",
        brand: "Adidas",
        price: 24.99,
        chance: 0.07,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    perfume: [
      {
        name: "Chanel No. 5",
        brand: "Chanel",
        price: 149.99,
        chance: 0.01,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Dior Sauvage",
        brand: "Dior",
        price: 119.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Bleu de Chanel",
        brand: "Chanel",
        price: 139.99,
        chance: 0.015,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Versace Eros",
        brand: "Versace",
        price: 89.99,
        chance: 0.03,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Armani Code",
        brand: "Armani",
        price: 99.99,
        chance: 0.025,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "YSL Black Opium",
        brand: "YSL",
        price: 109.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Calvin Klein Eternity",
        brand: "Calvin Klein",
        price: 69.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Hugo Boss Bottled",
        brand: "Hugo Boss",
        price: 79.99,
        chance: 0.035,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Travel Spray Set",
        brand: "Generic",
        price: 34.99,
        chance: 0.06,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Sample Set 10pc",
        brand: "Mixed",
        price: 24.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    car: [
      {
        name: "Dash Cam 4K",
        brand: "Garmin",
        price: 299.99,
        chance: 0.01,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Car Vacuum Wireless",
        brand: "Dyson",
        price: 249.99,
        chance: 0.01,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "LED Interior Kit",
        brand: "Generic",
        price: 49.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Phone Mount Wireless",
        brand: "iOttie",
        price: 59.99,
        chance: 0.03,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Tire Inflator",
        brand: "Generic",
        price: 39.99,
        chance: 0.05,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Seat Covers Premium",
        brand: "Generic",
        price: 79.99,
        chance: 0.03,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Car Freshener Set",
        brand: "Generic",
        price: 19.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Sunshade Umbrella",
        brand: "Generic",
        price: 24.99,
        chance: 0.07,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Car Wash Kit",
        brand: "Chemical Guys",
        price: 44.99,
        chance: 0.05,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Jump Starter",
        brand: "NOCO",
        price: 129.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    clothing: [
      {
        name: "Nike Tech Fleece",
        brand: "Nike",
        price: 119.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Adidas Originals Jacket",
        brand: "Adidas",
        price: 99.99,
        chance: 0.025,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Supreme Box Logo",
        brand: "Supreme",
        price: 299.99,
        chance: 0.005,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Off-White T-Shirt",
        brand: "Off-White",
        price: 249.99,
        chance: 0.008,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Levi's 501 Jeans",
        brand: "Levi's",
        price: 89.99,
        chance: 0.03,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Champion Hoodie",
        brand: "Champion",
        price: 69.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Carhartt WIP Beanie",
        brand: "Carhartt",
        price: 29.99,
        chance: 0.06,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Nike Socks 6-Pack",
        brand: "Nike",
        price: 24.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Cap Snapback",
        brand: "New Era",
        price: 34.99,
        chance: 0.05,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Graphic T-Shirt",
        brand: "Generic",
        price: 19.99,
        chance: 0.1,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    shoes: [
      {
        name: "Nike Air Max 90",
        brand: "Nike",
        price: 149.99,
        chance: 0.015,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Adidas Yeezy 350",
        brand: "Adidas",
        price: 299.99,
        chance: 0.005,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Jordan 4 Retro",
        brand: "Nike",
        price: 219.99,
        chance: 0.008,
        rarity: "epic",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "New Balance 550",
        brand: "New Balance",
        price: 129.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Converse Chuck 70",
        brand: "Converse",
        price: 89.99,
        chance: 0.03,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Vans Old Skool",
        brand: "Vans",
        price: 69.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Puma RS-X",
        brand: "Puma",
        price: 109.99,
        chance: 0.025,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Reebok Classic",
        brand: "Reebok",
        price: 79.99,
        chance: 0.035,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Shoe Care Kit",
        brand: "Crep",
        price: 34.99,
        chance: 0.06,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Sneaker Shields",
        brand: "Generic",
        price: 14.99,
        chance: 0.1,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    sweets: [
      {
        name: "Luxury Chocolate Box",
        brand: "Godiva",
        price: 79.99,
        chance: 0.02,
        rarity: "rare",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Japanese Candy Box",
        brand: "TokyoTreat",
        price: 49.99,
        chance: 0.03,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Lindt Gold Collection",
        brand: "Lindt",
        price: 39.99,
        chance: 0.04,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Haribo Giant Box",
        brand: "Haribo",
        price: 29.99,
        chance: 0.05,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "American Candy Mix",
        brand: "Mixed",
        price: 34.99,
        chance: 0.045,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Ferrero Rocher Tower",
        brand: "Ferrero",
        price: 44.99,
        chance: 0.035,
        rarity: "uncommon",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Kinder Surprise 24pc",
        brand: "Kinder",
        price: 24.99,
        chance: 0.06,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Toblerone Giant",
        brand: "Toblerone",
        price: 19.99,
        chance: 0.07,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "M&Ms Party Pack",
        brand: "M&Ms",
        price: 14.99,
        chance: 0.08,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Skittles Rainbow Box",
        brand: "Skittles",
        price: 9.99,
        chance: 0.1,
        rarity: "common",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
  }

  return contentByCategory[category] || contentByCategory.games
}
