export const categories = [
  { id: "games", name: "Igre", icon: "🎮", description: "Video igre i gaming oprema", glowColor: "#a855f7" },
  { id: "gaming", name: "Gaming", icon: "🕹️", description: "Gaming oprema i periferija", glowColor: "#ec4899" },
  { id: "tech", name: "Tech", icon: "💻", description: "Tehnologija i gadgeti", glowColor: "#3b82f6" },
  {
    id: "card-games",
    name: "Kartaške Igre",
    icon: "🃏",
    description: "Kolekcionarske i kartaške igre",
    glowColor: "#f59e0b",
  },
  { id: "tv", name: "TV", icon: "📺", description: "TV i streaming paketi", glowColor: "#ef4444" },
  { id: "sport", name: "Sport", icon: "⚽", description: "Sportska oprema i dodaci", glowColor: "#22c55e" },
  { id: "perfume", name: "Parfemi", icon: "🌸", description: "Luksuzni mirisi", glowColor: "#f472b6" },
  { id: "car", name: "Auto", icon: "🚗", description: "Auto oprema i dodaci", glowColor: "#64748b" },
  { id: "clothing", name: "Odjeća", icon: "👕", description: "Moda i odjeća", glowColor: "#8b5cf6" },
  { id: "shoes", name: "Obuća", icon: "👟", description: "Cipele i tenisice", glowColor: "#06b6d4" },
  { id: "sweets", name: "Slatkiši", icon: "🍬", description: "Slatke poslastice", glowColor: "#f97316" },
  { id: "home", name: "Dom", icon: "🏠", description: "Proizvodi za dom", glowColor: "#84cc16" },
  { id: "beach", name: "Plaža", icon: "🏖️", description: "Oprema za plažu i ljeto", glowColor: "#fbbf24" },
  { id: "jewelry", name: "Nakit", icon: "💎", description: "Luksuzni nakit i satovi", glowColor: "#c084fc" },
  { id: "gift-card", name: "Poklon Kartice", icon: "🎁", description: "Poklon bonovi i kartice", glowColor: "#fb7185" },
  { id: "music", name: "Glazba", icon: "🎵", description: "Glazbena oprema i instrumenti", glowColor: "#14b8a6" },
  { id: "bag", name: "Torbe", icon: "👜", description: "Torbe i ruksaci", glowColor: "#a78bfa" },
  { id: "watch", name: "Satovi", icon: "⌚", description: "Ručni satovi i pametni satovi", glowColor: "#60a5fa" },
]

export const products = [
  // SPORT CATEGORY (24 products)
  {
    id: "sport-fcb-lover",
    name: "FCB Lover Box",
    slug: "fcb-lover-box",
    category: "sport",
    price: 50,
    originalPrice: 120,
    image: "/images/01K1159R2V46DSP6851VG3WXQK.webp",
    dominantColor: "#004D98",
    rating: 4.8,
    reviews: 342,
    stock: 25,
    potentialValue: "Do 180€",
    description: "Sve za Barcelona fanove! Dres, šal i ekskluzivni FCB merchandise.",
    includes: ["FCB dres", "Navijački šal", "Zastava", "Kapa", "Bedž kolekcija"],
    gallery: ["/images/01K1159R2V46DSP6851VG3WXQK.webp"],
  },
  {
    id: "sport-basket",
    name: "Basket Box",
    slug: "basket-box",
    category: "sport",
    price: 50,
    originalPrice: 130,
    image: "/images/01J8CWHXD96R3Q61XRS4Q0PSWP.webp",
    dominantColor: "#FF6B35",
    rating: 4.7,
    reviews: 289,
    stock: 30,
    potentialValue: "Do 200€",
    description: "Košarkaški set! NBA merchandise, lopta i oprema.",
    includes: ["Košarkaška lopta", "NBA dres", "Ručnik", "Narukvica", "Čarape"],
    gallery: ["/images/01J8CWHXD96R3Q61XRS4Q0PSWP.webp"],
  },
  {
    id: "sport-baseball-100",
    name: "Baseball 100% Box",
    slug: "baseball-100-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01J8CWG61W16RP1ZAA0JJYJQ02.webp",
    dominantColor: "#C41E3A",
    rating: 4.9,
    reviews: 156,
    stock: 18,
    potentialValue: "Do 250€",
    description: "Profesionalni baseball set! Rukavica, lopta i MLB memorabilije.",
    includes: ["Baseball rukavica", "Službena lopta", "MLB kapa", "Bejzbol majica", "Autogram poster"],
    gallery: ["/images/01J8CWG61W16RP1ZAA0JJYJQ02.webp"],
  },
  {
    id: "sport-real",
    name: "Real Box",
    slug: "real-box",
    category: "sport",
    price: 50,
    originalPrice: 115,
    image: "/images/01K1159NTHVJW6317M8M8EJ95T.webp",
    dominantColor: "#FEBE10",
    rating: 4.8,
    reviews: 421,
    stock: 28,
    potentialValue: "Do 170€",
    description: "Hala Madrid! Real Madrid merchandise i navijačka oprema.",
    includes: ["Real Madrid dres", "Šal", "Privjesci", "Poster set", "Bedž kolekcija"],
    gallery: ["/images/01K1159NTHVJW6317M8M8EJ95T.webp"],
  },
  {
    id: "sport-touchdown",
    name: "Touchdown Box",
    slug: "touchdown-box",
    category: "sport",
    price: 90,
    originalPrice: 220,
    image: "/images/01J8CWKDKM3VF0MXW3XGT9X864.webp",
    dominantColor: "#013369",
    rating: 4.9,
    reviews: 187,
    stock: 15,
    potentialValue: "Do 300€",
    description: "NFL excitement! Američki nogomet oprema i NFL merchandise.",
    includes: ["NFL dres", "Američka lopta", "Kaciga mini", "Rukavice", "Team flag"],
    gallery: ["/images/01J8CWKDKM3VF0MXW3XGT9X864.webp"],
  },
  {
    id: "sport-manchester-city",
    name: "Manchester City Box",
    slug: "manchester-city-box",
    category: "sport",
    price: 50,
    originalPrice: 125,
    image: "/images/01K1159HBN6EYMD1T7J1XJB1MZ.webp",
    dominantColor: "#6CABDD",
    rating: 4.7,
    reviews: 345,
    stock: 32,
    potentialValue: "Do 190€",
    description: "Citizens pride! Manchester City dres i navijačka kolekcija.",
    includes: ["Man City dres", "Šal", "Kapa", "Bedž set", "Narukvica"],
    gallery: ["/images/01K1159HBN6EYMD1T7J1XJB1MZ.webp"],
  },
  {
    id: "sport-ufc-fighter",
    name: "UFC Fighter Box",
    slug: "ufc-fighter-box",
    category: "sport",
    price: 75,
    originalPrice: 175,
    image: "/images/01HVC94BETCTB16E49S672YKRY.webp",
    dominantColor: "#D20A0A",
    rating: 4.8,
    reviews: 234,
    stock: 20,
    potentialValue: "Do 260€",
    description: "Fight gear! UFC oprema za treninge i borbe.",
    includes: ["MMA rukavice", "Bandaže", "Majica", "Šorts", "Trening oprema"],
    gallery: ["/images/01HVC94BETCTB16E49S672YKRY.webp"],
  },
  {
    id: "sport-golf",
    name: "Golf Box",
    slug: "golf-box",
    category: "sport",
    price: 75,
    originalPrice: 190,
    image: "/images/01J8CWMYAV86A5FRJ1E4Y9V30C.webp",
    dominantColor: "#1E7B3C",
    rating: 4.6,
    reviews: 128,
    stock: 22,
    potentialValue: "Do 280€",
    description: "Gentleman's sport! Golf oprema i dodaci za savršen swing.",
    includes: ["Golf rukavice", "Lopte set", "Tee set", "Kapa", "Ručnik"],
    gallery: ["/images/01J8CWMYAV86A5FRJ1E4Y9V30C.webp"],
  },
  {
    id: "sport-rugby-love",
    name: "Rugby Love Box",
    slug: "rugby-love-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01JN6CY10CPE3FWADRTB8A501K.webp",
    dominantColor: "#8B4513",
    rating: 4.7,
    reviews: 167,
    stock: 19,
    potentialValue: "Do 250€",
    description: "Rough and tough! Rugby oprema i international merchandise.",
    includes: ["Rugby lopta", "Dres", "Zaštitna oprema", "Čarape", "Trening dodaci"],
    gallery: ["/images/01JN6CY10CPE3FWADRTB8A501K.webp"],
  },
  {
    id: "sport-mix",
    name: "Sport Mix Box",
    slug: "sport-mix-box",
    category: "sport",
    price: 100,
    originalPrice: 250,
    image: "/images/01J3CY0GSJ3KNE28HDZ09YN1J0.webp",
    dominantColor: "#FF6B35",
    rating: 4.9,
    reviews: 456,
    stock: 12,
    potentialValue: "Do 400€",
    description: "Najbolje od svega! Mix sportske opreme iz raznih sportova.",
    includes: ["Multi-sport oprema", "Brendirana odjeća", "Lopte", "Dodaci", "Surprise items"],
    gallery: ["/images/01J3CY0GSJ3KNE28HDZ09YN1J0.webp"],
  },
  {
    id: "sport-padel-ace",
    name: "Padel Ace Box",
    slug: "padel-ace-box",
    category: "sport",
    price: 75,
    originalPrice: 185,
    image: "/images/01JN6CY72MWF0PHKY5MWV8K561.webp",
    dominantColor: "#FFD700",
    rating: 4.8,
    reviews: 198,
    stock: 16,
    potentialValue: "Do 270€",
    description: "Padel revolution! Oprema za najbrže rastući sport.",
    includes: ["Padel lopte", "Grip tape", "Rukavice", "Majica", "Torba"],
    gallery: ["/images/01JN6CY72MWF0PHKY5MWV8K561.webp"],
  },
  {
    id: "sport-checkmate",
    name: "Checkmate Box",
    slug: "checkmate-box",
    category: "sport",
    price: 50,
    originalPrice: 120,
    image: "/images/01JEYJBGWMH92NRQ2F7M5PRNSG.webp",
    dominantColor: "#2C2C2C",
    rating: 4.5,
    reviews: 234,
    stock: 35,
    potentialValue: "Do 160€",
    description: "Šah je sport uma! Profesionalne figure i šahovska oprema.",
    includes: ["Šahovska ploča", "Figure set", "Šahovski sat", "Knjiga", "Torba za figure"],
    gallery: ["/images/01JEYJBGWMH92NRQ2F7M5PRNSG.webp"],
  },
  {
    id: "sport-bayern",
    name: "Bayern Box",
    slug: "bayern-box",
    category: "sport",
    price: 50,
    originalPrice: 125,
    image: "/images/01K1159KMJ0N80W96EWHP2AHM6.webp",
    dominantColor: "#DC052D",
    rating: 4.9,
    reviews: 389,
    stock: 24,
    potentialValue: "Do 185€",
    description: "Mia san mia! Bayern Munich official merchandise.",
    includes: ["Bayern dres", "Šal", "Kapa", "Bedž set", "Zastava"],
    gallery: ["/images/01K1159KMJ0N80W96EWHP2AHM6.webp"],
  },
  {
    id: "sport-sparring",
    name: "Sparring Box",
    slug: "sparring-box",
    category: "sport",
    price: 75,
    originalPrice: 175,
    image: "/images/01J1SGFDFY5Z6HGD47HKWWHC1N.webp",
    dominantColor: "#C41E3A",
    rating: 4.7,
    reviews: 267,
    stock: 21,
    potentialValue: "Do 240€",
    description: "Boksačka oprema! Sve za trening i sparring.",
    includes: ["Boksačke rukavice", "Bandaže", "Zaštitnik zubi", "Trening torba", "Oprema"],
    gallery: ["/images/01J1SGFDFY5Z6HGD47HKWWHC1N.webp"],
  },
  {
    id: "sport-euro",
    name: "Euro Box",
    slug: "euro-box",
    category: "sport",
    price: 100,
    originalPrice: 240,
    image: "/images/01J09RAYHE1MZZC7AFMZT7KEZ3.webp",
    dominantColor: "#0055A4",
    rating: 4.9,
    reviews: 512,
    stock: 10,
    potentialValue: "Do 350€",
    description: "European football! Najbolje od EURO turnira.",
    includes: ["Službena lopta", "Multi dres", "Šalovi", "Memorabilije", "VIP dodaci"],
    gallery: ["/images/01J09RAYHE1MZZC7AFMZT7KEZ3.webp"],
  },
  {
    id: "sport-football-lover",
    name: "Football Lover",
    slug: "football-lover",
    category: "sport",
    price: 50,
    originalPrice: 130,
    image: "/images/01HNCX89C1AP1NDM0GD4X4FCG9.webp",
    dominantColor: "#00A651",
    rating: 4.8,
    reviews: 678,
    stock: 40,
    potentialValue: "Do 200€",
    description: "Za prave ljubitelje nogometa! Oprema i fan merchandise.",
    includes: ["Nogometna lopta", "Dres", "Šal", "Čarape", "Trening dodaci"],
    gallery: ["/images/01HNCX89C1AP1NDM0GD4X4FCG9.webp"],
  },
  {
    id: "sport-ride-n-slide",
    name: "Ride n Slide Box",
    slug: "ride-n-slide-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01JC5YBT3521YGHF7GV6HC97VW.webp",
    dominantColor: "#FF6B35",
    rating: 4.6,
    reviews: 189,
    stock: 17,
    potentialValue: "Do 260€",
    description: "Skate and surf! Oprema za ekstremne sportove.",
    includes: ["Skateboard dodaci", "Zaštitna oprema", "Majica", "Naljepnice", "Grip tape"],
    gallery: ["/images/01JC5YBT3521YGHF7GV6HC97VW.webp"],
  },
  {
    id: "sport-mountain-rider",
    name: "Mountain Rider Box",
    slug: "mountain-rider-box",
    category: "sport",
    price: 100,
    originalPrice: 250,
    image: "/images/01JFG28H45890ANCT44P1E0ED2.webp",
    dominantColor: "#228B22",
    rating: 4.9,
    reviews: 234,
    stock: 14,
    potentialValue: "Do 380€",
    description: "MTB adventure! Mountain bike oprema i dodaci.",
    includes: ["Bike dodaci", "Zaštitna oprema", "Rukavice", "Boca", "Tools set"],
    gallery: ["/images/01JFG28H45890ANCT44P1E0ED2.webp"],
  },
  {
    id: "sport-rock-ride",
    name: "Rock Ride Box",
    slug: "rock-ride-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01JC5NSMP8PW0KPEKF0073SX21.webp",
    dominantColor: "#A9A9A9",
    rating: 4.7,
    reviews: 156,
    stock: 19,
    potentialValue: "Do 270€",
    description: "Climbing gear! Oprema za penjanje i bouldering.",
    includes: ["Penjačke rukavice", "Chalk bag", "Karabiner set", "Majica", "Dodaci"],
    gallery: ["/images/01JC5NSMP8PW0KPEKF0073SX21.webp"],
  },
  {
    id: "sport-fit-fury",
    name: "Fit Fury Box",
    slug: "fit-fury-box",
    category: "sport",
    price: 50,
    originalPrice: 125,
    image: "/images/01JN6CY3YG68SCQ4QWDJZXEQ2Q.webp",
    dominantColor: "#FF4500",
    rating: 4.8,
    reviews: 445,
    stock: 33,
    potentialValue: "Do 190€",
    description: "Fitness revolution! Gym oprema i dodaci za trening.",
    includes: ["Resistance bands", "Rukavice", "Boca", "Ručnik", "Suplementi"],
    gallery: ["/images/01JN6CY3YG68SCQ4QWDJZXEQ2Q.webp"],
  },
  {
    id: "sport-psg-pro",
    name: "PSG Pro Box",
    slug: "psg-pro-box",
    category: "sport",
    price: 50,
    originalPrice: 120,
    image: "/images/01K1159TXMJH8ARSKG7NNAD73Y.webp",
    dominantColor: "#004170",
    rating: 4.9,
    reviews: 567,
    stock: 26,
    potentialValue: "Do 180€",
    description: "Ici c'est Paris! PSG official merchandise i navijačka oprema.",
    includes: ["PSG dres", "Šal", "Kapa", "Bedž kolekcija", "Poster"],
    gallery: ["/images/01K1159TXMJH8ARSKG7NNAD73Y.webp"],
  },
  {
    id: "sport-athletic",
    name: "Athletic Box",
    slug: "athletic-box",
    category: "sport",
    price: 35,
    originalPrice: 85,
    image: "/images/01HPGXQD96PD4VJHA84KBE60GE.webp",
    dominantColor: "#00A8E1",
    rating: 4.6,
    reviews: 289,
    stock: 45,
    potentialValue: "Do 140€",
    description: "Atletika oprema! Sve za trčanje i atletske discipline.",
    includes: ["Running majica", "Čarape", "Traka za glavu", "Boca", "Timing watch"],
    gallery: ["/images/01HPGXQD96PD4VJHA84KBE60GE.webp"],
  },
  {
    id: "sport-tennis",
    name: "Tennis Box",
    slug: "tennis-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01JN6CXV3ETN4MMZKKQ7FRYRCS.webp",
    dominantColor: "#CCFF00",
    rating: 4.7,
    reviews: 198,
    stock: 20,
    potentialValue: "Do 250€",
    description: "Game, set, match! Teniski set i profesionalna oprema.",
    includes: ["Tenis lopte", "Grip tape", "Znojnica", "Torba", "Ručnik"],
    gallery: ["/images/01JN6CXV3ETN4MMZKKQ7FRYRCS.webp"],
  },

  // PERFUME CATEGORY (2 products)
  {
    id: "perfume-box",
    name: "Perfume Box",
    slug: "perfume-box",
    category: "perfume",
    price: 50,
    originalPrice: 140,
    image: "/images/01JRMPW8V0MFRW5NA1RG94CGD1.webp",
    dominantColor: "#FFD700", // Gold perfume
    rating: 4.8,
    reviews: 892,
    stock: 35,
    potentialValue: "Do 250€",
    description: "Luksuzni mirisi! Designer parfemi i niche fragrances.",
    includes: ["Parfem 50ml+", "Travel size", "Cologne", "Samples set", "Giftbox"],
    gallery: ["/images/01JRMPW8V0MFRW5NA1RG94CGD1.webp"],
  },
  {
    id: "perfume-rituals",
    name: "Rituals Box",
    slug: "rituals-box",
    category: "perfume",
    price: 75,
    originalPrice: 180,
    image: "/images/01JNRFA9YJ7FJFFGD48SJJE1QJ.webp",
    dominantColor: "#D4AF37", // Rituals gold
    rating: 4.9,
    reviews: 567,
    stock: 22,
    potentialValue: "Do 280€",
    description: "Wellness rituali! Rituals proizvodi za njegu i mirise.",
    includes: ["Body cream", "Shower gel", "Parfem", "Świeca", "Gift set"],
    gallery: ["/images/01JNRFA9YJ7FJFFGD48SJJE1QJ.webp"],
  },

  // SHOES CATEGORY (7 products)
  {
    id: "shoes-dunk-dream",
    name: "Dunk Dream Box",
    slug: "dunk-dream-box",
    category: "shoes",
    price: 75,
    originalPrice: 200,
    image: "/images/01HNDH7QRZGWTWZ1WQAXNM0XHP.webp",
    dominantColor: "#1E90FF", // Dunk blue
    rating: 4.9,
    reviews: 678,
    stock: 15,
    potentialValue: "Do 350€",
    description: "Nike Dunk kolekcija! Limitirane Dunk tenisice i dodaci.",
    includes: ["Nike Dunk", "Crep protect", "Laces set", "Stickers", "Box"],
    gallery: ["/images/01HNDH7QRZGWTWZ1WQAXNM0XHP.webp"],
  },
  {
    id: "shoes-sneakers-drip",
    name: "Sneakers Drip",
    slug: "sneakers-drip",
    category: "shoes",
    price: 75,
    originalPrice: 185,
    image: "/images/01HNCWBMYMCQBPB72FZFEE01NC.webp",
    dominantColor: "#32CD32", // Sneaker green
    rating: 4.8,
    reviews: 543,
    stock: 18,
    potentialValue: "Do 320€",
    description: "Sneaker game! Retro i moderne tenisice.",
    includes: ["Branded sneakers", "Čistač", "Extra laces", "Shoe horn", "Bag"],
    gallery: ["/images/01HNCWBMYMCQBPB72FZFEE01NC.webp"],
  },
  {
    id: "shoes-jordans",
    name: "Jordans Box",
    slug: "jordans-box",
    category: "shoes",
    price: 75,
    originalPrice: 195,
    image: "/images/01K2PH91T089TBK5YSF5P6H3R1.webp",
    dominantColor: "#DC143C", // Jordan red
    rating: 4.9,
    reviews: 834,
    stock: 12,
    potentialValue: "Do 400€",
    description: "Jumpman legacy! Air Jordan tenisice i merchandise.",
    includes: ["Air Jordan", "Jordan majica", "Caps", "Socks", "Keychain"],
    gallery: ["/images/01K2PH91T089TBK5YSF5P6H3R1.webp"],
  },
  {
    id: "shoes-la-flame",
    name: "La Flame Box",
    slug: "la-flame-box",
    category: "shoes",
    price: 100,
    originalPrice: 260,
    image: "/images/01HND7FHPVFHKY7RCHB9XM1JYM.webp",
    dominantColor: "#8B4513", // Travis brown
    rating: 4.9,
    reviews: 456,
    stock: 8,
    potentialValue: "Do 500€",
    description: "Travis Scott kolabs! Cactus Jack tenisice i merch.",
    includes: ["Travis collab shoes", "Hoodie", "Vinyl", "Poster", "Stickers"],
    gallery: ["/images/01HND7FHPVFHKY7RCHB9XM1JYM.webp"],
  },
  {
    id: "shoes-dunks-lover",
    name: "Dunks Lover",
    slug: "dunks-lover",
    category: "shoes",
    price: 150,
    originalPrice: 400,
    image: "/images/01HS6MBE697BFSB2VX7FDV3J9F.webp",
    dominantColor: "#FF69B4", // Premium pink
    rating: 5.0,
    reviews: 234,
    stock: 5,
    potentialValue: "Do 800€",
    description: "Premium Dunk! Rijetke i limitirane Nike Dunk tenisice.",
    includes: ["Rare Dunks", "Premium box", "Certificate", "Cleaning kit", "Display stand"],
    gallery: ["/images/01HS6MBE697BFSB2VX7FDV3J9F.webp"],
  },
  {
    id: "shoes-subscription",
    name: "Shoes Subscription Box",
    slug: "shoes-subscription-box",
    category: "shoes",
    price: 50,
    originalPrice: 130,
    image: "/images/01HNCWA365FN0EK2PQFMS1E734.webp",
    dominantColor: "#00CED1", // Subscription cyan
    rating: 4.7,
    reviews: 389,
    stock: 28,
    potentialValue: "Do 220€",
    description: "Mjesečno iznenađenje! Subscription box s tenisicama.",
    includes: ["Branded shoes", "Accessories", "Socks", "Care kit", "Surprise items"],
    gallery: ["/images/01HNCWA365FN0EK2PQFMS1E734.webp"],
  },
  {
    id: "shoes-step-up",
    name: "Step Up Box",
    slug: "step-up-box",
    category: "shoes",
    price: 75,
    originalPrice: 180,
    image: "/images/01HNDBSSDXQMX0TSXGC46H4ZMR.webp",
    dominantColor: "#FFD700", // Step up gold
    rating: 4.8,
    reviews: 467,
    stock: 20,
    potentialValue: "Do 300€",
    description: "Lifestyle footwear! Casual i street style tenisice.",
    includes: ["Lifestyle shoes", "Insoles", "Laces pack", "Cleaner", "Bag"],
    gallery: ["/images/01HNDBSSDXQMX0TSXGC46H4ZMR.webp"],
  },

  // SWEETS CATEGORY (1 product)
  {
    id: "sweets-surprise",
    name: "Sweet Surprise Box",
    slug: "sweet-surprise-box",
    category: "sweets",
    price: 20,
    originalPrice: 50,
    image: "/images/01KB530GDAPH6DVN62K7TT06MK.webp",
    dominantColor: "#FF1493", // Candy pink
    rating: 4.9,
    reviews: 1234,
    stock: 89,
    potentialValue: "Do 80€",
    description: "Slatkiši iz cijelog svijeta! Candy, čokolade i poslastice.",
    includes: ["Import candy", "Čokolade", "Gumeni bomboni", "Snacks", "Surprise treat"],
    gallery: ["/images/01KB530GDAPH6DVN62K7TT06MK.webp"],
  },

  // HOME CATEGORY (6 products)
  {
    id: "home-vintage-treasures",
    name: "Vintage Treasures",
    slug: "vintage-treasures",
    category: "home",
    price: 50,
    originalPrice: 130,
    image: "/images/01KDDWZ5SHK63F2JEGBNQREHK9.webp",
    dominantColor: "#8B7355", // Vintage brown
    rating: 4.7,
    reviews: 234,
    stock: 18,
    potentialValue: "Do 220€",
    description: "Vintage dekor! Retro predmeti za dom.",
    includes: ["Vintage dekor", "Retro poster", "Svijeća", "Ukras", "Collectibles"],
    gallery: ["/images/01KDDWZ5SHK63F2JEGBNQREHK9.webp"],
  },
  {
    id: "home-luxury",
    name: "Home Luxury Box",
    slug: "home-luxury-box",
    category: "home",
    price: 75,
    originalPrice: 190,
    image: "/images/01KBPZEMQG0SM2376QJH82SQCB.webp",
    dominantColor: "#FFD700", // Luxury gold
    rating: 4.9,
    reviews: 456,
    stock: 14,
    potentialValue: "Do 300€",
    description: "Luksuz za dom! Premium predmeti i dekoracije.",
    includes: ["Luxury dekor", "Svijeće", "Diffuser", "Throw blanket", "Premium ukras"],
    gallery: ["/images/01KBPZEMQG0SM2376QJH82SQCB.webp"],
  },
  {
    id: "home-design",
    name: "Home Design Box",
    slug: "home-design-box",
    category: "home",
    price: 75,
    originalPrice: 185,
    image: "/images/01HWD335QCGV3WGMF299TXNPJH.webp",
    dominantColor: "#4169E1", // Design blue
    rating: 4.8,
    reviews: 378,
    stock: 16,
    potentialValue: "Do 280€",
    description: "Designer komadi! Moderni predmeti za uređenje doma.",
    includes: ["Design lighting", "Wall art", "Dekor", "Tekstil", "Modern pieces"],
    gallery: ["/images/01HWD335QCGV3WGMF299TXNPJH.webp"],
  },
  {
    id: "home-grill-master",
    name: "Grill Master Box",
    slug: "grill-master-box",
    category: "home",
    price: 100,
    originalPrice: 250,
    image: "/images/01JZWDP0H67BQYTYY71AGTC6SW.webp",
    dominantColor: "#FF4500", // Grill orange
    rating: 4.9,
    reviews: 567,
    stock: 12,
    potentialValue: "Do 400€",
    description: "BBQ essentials! Sve za savršeno roštiljanje.",
    includes: ["Grill tools set", "Spices", "Apron", "Termometar", "Cleaning kit"],
    gallery: ["/images/01JZWDP0H67BQYTYY71AGTC6SW.webp"],
  },
  {
    id: "home-box",
    name: "Home Box",
    slug: "home-box",
    category: "home",
    price: 50,
    originalPrice: 125,
    image: "/images/01HQJ8WCKMJB52KCMCA4XHE68A.webp",
    dominantColor: "#32CD32", // Home green
    rating: 4.7,
    reviews: 689,
    stock: 30,
    potentialValue: "Do 200€",
    description: "Praktični predmeti za dom! Kuhinja, kupaonica, dnevni boravak.",
    includes: ["Kitchen gadgets", "Dekor", "Tekstil", "Organizatori", "Useful items"],
    gallery: ["/images/01HQJ8WCKMJB52KCMCA4XHE68A.webp"],
  },
  {
    id: "home-magic-night",
    name: "Magic Night Box",
    slug: "magic-night-box",
    category: "home",
    price: 50,
    originalPrice: 135,
    image: "/images/01KD0T4WX80C1AZM6M9MN5RB16 (1).webp",
    dominantColor: "#9370DB", // Purple ambient
    rating: 4.8,
    reviews: 445,
    stock: 22,
    potentialValue: "Do 210€",
    description: "Romantična atmosfera! LED rasvjeta i ambient lighting.",
    includes: ["LED lights", "Svijeće", "Diffuser", "Soft blanket", "Mood lighting"],
    gallery: ["/images/01KD0T4WX80C1AZM6M9MN5RB16 (1).webp"],
  },

  // CAR CATEGORY (5 products)
  {
    id: "car-50-50-bikes",
    name: "50-50 Bikes",
    slug: "50-50-bikes",
    category: "car",
    price: 650,
    originalPrice: 1500,
    image: "/images/01JVY8E72R8GET3JF1EHH5CVPF.webp",
    dominantColor: "#FF6B35", // Bike orange
    rating: 5.0,
    reviews: 89,
    stock: 3,
    potentialValue: "Do 3000€",
    description: "50% šansa za high-end bicikl! Premium cycling oprema.",
    includes: ["Premium bike / accessories", "Helmet", "Gear", "Maintenance kit", "Cycling wear"],
    gallery: ["/images/01JVY8E72R8GET3JF1EHH5CVPF.webp"],
  },
  {
    id: "car-suzukis-obsession",
    name: "Suzukis Obsession",
    slug: "suzukis-obsession",
    category: "car",
    price: 650,
    originalPrice: 1500,
    image: "/images/01K9RGE6C66RWVZCXNX43CJTGY.webp",
    dominantColor: "#0033A0", // Suzuki blue
    rating: 4.9,
    reviews: 67,
    stock: 2,
    potentialValue: "Do 3000€",
    description: "Suzuki motocikl! Premium motorcycle gear i dodaci.",
    includes: ["Suzuki merch", "Riding gear", "Helmet accessories", "Tools", "Premium items"],
    gallery: ["/images/01K9RGE6C66RWVZCXNX43CJTGY.webp"],
  },
  {
    id: "car-yamaha-madness",
    name: "Yamaha Madness Box",
    slug: "yamaha-madness-box",
    category: "car",
    price: 650,
    originalPrice: 1500,
    image: "/images/01K0N2TWXMXSM3R7WHJ3KNXKXE.webp",
    dominantColor: "#000080", // Yamaha navy
    rating: 4.9,
    reviews: 78,
    stock: 4,
    potentialValue: "Do 3000€",
    description: "Yamaha moto oprema! Premium motorcycle accessories.",
    includes: ["Yamaha gear", "Riding equipment", "Premium helmet", "Tools", "Merch"],
    gallery: ["/images/01K0N2TWXMXSM3R7WHJ3KNXKXE.webp"],
  },
  {
    id: "car-automotive-elite",
    name: "Automotive Elite",
    slug: "automotive-elite",
    category: "car",
    price: 50,
    originalPrice: 130,
    image: "/images/01JRC5M8RJVFTNMGXVRMVAQH80.webp",
    dominantColor: "#C0C0C0", // Chrome silver
    rating: 4.8,
    reviews: 345,
    stock: 20,
    potentialValue: "Do 220€",
    description: "Auto oprema! Premium dodaci za vaš automobil.",
    includes: ["Auto gadgets", "Cleaning kit", "Air freshener", "Accessories", "Tools"],
    gallery: ["/images/01JRC5M8RJVFTNMGXVRMVAQH80.webp"],
  },
  {
    id: "car-bikers-bounty",
    name: "Bikers Bounty Box",
    slug: "bikers-bounty-box",
    category: "car",
    price: 75,
    originalPrice: 180,
    image: "/images/01K4JEVHFBK9TDXHRW8F0D1M7V.webp",
    dominantColor: "#FF4500", // Biker orange
    rating: 4.8,
    reviews: 234,
    stock: 15,
    potentialValue: "Do 280€",
    description: "Biker lifestyle! Motociklističke rukavice i oprema.",
    includes: ["Riding gloves", "Bandana", "Patch set", "Keychain", "Accessories"],
    gallery: ["/images/01K4JEVHFBK9TDXHRW8F0D1M7V.webp"],
  },

  // MUSIC CATEGORY (5 products)
  {
    id: "music-rock-with-you",
    name: "Rock with You Box",
    slug: "rock-with-you-box",
    category: "music",
    price: 50,
    originalPrice: 130,
    image: "/images/01HQZNF35QBXT1DV44M6BWVHQF.webp",
    dominantColor: "#DC143C", // Rock red
    rating: 4.8,
    reviews: 456,
    stock: 22,
    potentialValue: "Do 200€",
    description: "Rock legends! Vintage band merchandise i memorabilije.",
    includes: ["Band tees", "Vinyl records", "Poster set", "Patches", "Pick collection"],
    gallery: ["/images/01HQZNF35QBXT1DV44M6BWVHQF.webp"],
  },
  {
    id: "music-vinyl-vibes",
    name: "Vinyl Vibes",
    slug: "vinyl-vibes",
    category: "music",
    price: 75,
    originalPrice: 180,
    image: "/images/01K3EEK22W4KG9AKDV0FZ3WRZW.webp",
    dominantColor: "#2F4F4F", // Vinyl black
    rating: 4.9,
    reviews: 234,
    stock: 18,
    potentialValue: "Do 280€",
    description: "Vinyl kolekcija! Rijetke ploče i oprema za gramofonsku.",
    includes: ["Vinyl records", "Cleaning kit", "Sleeves", "Turntable accessories", "Collectibles"],
    gallery: ["/images/01K3EEK22W4KG9AKDV0FZ3WRZW.webp"],
  },
  {
    id: "music-king-of-pop",
    name: "King of the Pop Box",
    slug: "king-of-pop-box",
    category: "music",
    price: 100,
    originalPrice: 250,
    image: "/images/01HP07YE8VH9PS7M56EVBPB3TF.webp",
    dominantColor: "#FFD700", // MJ gold
    rating: 4.9,
    reviews: 567,
    stock: 12,
    potentialValue: "Do 400€",
    description: "Michael Jackson tribute! Legendarni king of pop merchandise.",
    includes: ["Limited edition merch", "Vinyl records", "Poster collection", "Memorabilia", "Certificate"],
    gallery: ["/images/01HP07YE8VH9PS7M56EVBPB3TF.webp"],
  },
  {
    id: "music-hip-hop-classic",
    name: "Hip Hop Classic Box",
    slug: "hip-hop-classic-box",
    category: "music",
    price: 75,
    originalPrice: 180,
    image: "/images/01HPG8XQGMR99R4CG7HPDAYBDV.webp",
    dominantColor: "#FFD700", // Hip hop gold
    rating: 4.8,
    reviews: 389,
    stock: 20,
    potentialValue: "Do 270€",
    description: "Hip hop kultura! 90s rap merchandise i streetwear.",
    includes: ["Hip hop tees", "Caps", "Vinyl records", "Stickers", "Collector items"],
    gallery: ["/images/01HPG8XQGMR99R4CG7HPDAYBDV.webp"],
  },
  {
    id: "music-maestro",
    name: "The Maestro Box",
    slug: "maestro-box",
    category: "music",
    price: 100,
    originalPrice: 240,
    image: "/images/01K0MBXANAWQFP73F77EZ01MR1.webp",
    dominantColor: "#8B4513", // Classical brown
    rating: 4.9,
    reviews: 178,
    stock: 14,
    potentialValue: "Do 350€",
    description: "Klasična glazba! Orkestralna oprema i dirigent set.",
    includes: ["Sheet music", "Conductor baton", "Classical vinyl", "Books", "Premium items"],
    gallery: ["/images/01K0MBXANAWQFP73F77EZ01MR1.webp"],
  },

  // CLOTHING CATEGORY (30 products)
  {
    id: "clothing-minecraft",
    name: "Minecraft Box",
    slug: "minecraft-box",
    category: "games", // Changed category to "games" as per the update
    tag: "digital",
    price: 35,
    originalPrice: 89,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp",
    dominantColor: "#00AA00", // Minecraft green
    rating: 4.8,
    reviews: 1234,
    stock: 50,
    potentialValue: "Do 150€",
    description: "Minecraft svijet! Igra, merchandise i blockout dodatci.",
    includes: ["Minecraft账号", "Premium skin", "Merch", "Stickers", "Poster"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-executive-ceo",
    name: "Executive CEO Box",
    slug: "executive-ceo-box",
    category: "clothing",
    price: 100,
    originalPrice: 260,
    image: "/images/01HQJ8WCKMJB52KCMCA4XHE68A.webp", // Placeholder image replaced
    dominantColor: "#4682B4", // Steel blue for executive
    rating: 4.9,
    reviews: 345,
    stock: 15,
    potentialValue: "Do 450€",
    description: "Business luksuz! Premium odijela, košulje i dodaci.",
    includes: ["Designer shirt", "Tie", "Cufflinks", "Belt", "Luxury accessories"],
    gallery: ["/images/01HQJ8WCKMJB52KCMCA4XHE68A.webp"],
  },
  {
    id: "clothing-balenciaga-prada",
    name: "Balenciaga X Prada Box",
    slug: "balenciaga-prada-box",
    category: "clothing",
    price: 100,
    originalPrice: 280,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#000000", // Black for high fashion
    rating: 5.0,
    reviews: 234,
    stock: 8,
    potentialValue: "Do 600€",
    description: "High fashion! Balenciaga i Prada komadi i dodaci.",
    includes: ["Designer piece", "Accessories", "Bag", "Sunglasses", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-chrome-hearts",
    name: "Chrome Hearts Box",
    slug: "chrome-hearts-box",
    category: "clothing",
    price: 75,
    originalPrice: 190,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#A9A9A9", // Dark gray for chrome
    rating: 4.9,
    reviews: 456,
    stock: 12,
    potentialValue: "Do 400€",
    description: "Rock luxury! Chrome Hearts nakit i odjeća.",
    includes: ["CH jewelry", "T-shirt", "Accessories", "Ring", "Premium items"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-chanel",
    name: "Chanel Box",
    slug: "chanel-box",
    category: "clothing",
    price: 100,
    originalPrice: 270,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#C0C0C0", // Silver for Chanel elegance
    rating: 5.0,
    reviews: 567,
    stock: 10,
    potentialValue: "Do 550€",
    description: "Iconic elegance! Chanel parfemi, dodaci i odjeća.",
    includes: ["Chanel perfume", "Accessories", "Makeup", "Bag", "Luxury item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-celine",
    name: "Celine Box",
    slug: "celine-box",
    category: "clothing",
    price: 75,
    originalPrice: 185,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#6A5ACD", // Slate blue for Parisian chic
    rating: 4.8,
    reviews: 289,
    stock: 14,
    potentialValue: "Do 380€",
    description: "Parisian chic! Celine torbe i fashion dodaci.",
    includes: ["Celine accessory", "Wallet", "Sunglasses", "Scarf", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-palm-angels",
    name: "Palm Angels Box",
    slug: "palm-angels-box",
    category: "clothing",
    price: 50,
    originalPrice: 135,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FFA07A", // Light salmon for LA vibe
    rating: 4.9,
    reviews: 678,
    stock: 22,
    potentialValue: "Do 250€",
    description: "LA streetwear! Palm Angels hoodie, majice i dodaci.",
    includes: ["PA hoodie/tee", "Cap", "Socks", "Stickers", "Accessories"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-maison-goyard",
    name: "Maison Goyard Box",
    slug: "maison-goyard-box",
    category: "clothing",
    price: 180,
    originalPrice: 450,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#8B4513", // Brown for Goyard classic
    rating: 5.0,
    reviews: 123,
    stock: 5,
    potentialValue: "Do 900€",
    description: "French luxury! Goyard torbe i premium dodaci.",
    includes: ["Goyard bag", "Wallet", "Cardholder", "Accessories", "Authentication"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-spoiled-wife",
    name: "Spoiled Wife Box",
    slug: "spoiled-wife-box",
    category: "clothing",
    price: 50,
    originalPrice: 140,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FFB6C1", // Light pink for feminine luxury
    rating: 4.8,
    reviews: 890,
    stock: 28,
    potentialValue: "Do 260€",
    description: "Luxury lifestyle! Designer dodaci za žene.",
    includes: ["Designer item", "Jewelry", "Perfume", "Makeup", "Luxury treats"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-ysl-signature",
    name: "YSL Signature",
    slug: "ysl-signature",
    category: "clothing",
    price: 100,
    originalPrice: 260,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#800080", // Purple for YSL sophistication
    rating: 4.9,
    reviews: 445,
    stock: 11,
    potentialValue: "Do 500€",
    description: "Saint Laurent! YSL torbe, parfemi i fashion.",
    includes: ["YSL bag/perfume", "Accessories", "Makeup", "Scarf", "Luxury item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-prada-privilege",
    name: "Prada Privilege Box",
    slug: "prada-privilege-box",
    category: "clothing",
    price: 75,
    originalPrice: 200,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#A52A2A", // Brown for Prada sophistication
    rating: 5.0,
    reviews: 356,
    stock: 13,
    potentialValue: "Do 420€",
    description: "Italian luxury! Prada torbe i high fashion dodaci.",
    includes: ["Prada accessory", "Wallet", "Keychain", "Sunglasses", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-top-g",
    name: "Top G Box",
    slug: "top-g-box",
    category: "clothing",
    price: 250,
    originalPrice: 600,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#B8860B", // Dark goldenrod for "Top G" vibe
    rating: 5.0,
    reviews: 189,
    stock: 4,
    potentialValue: "Do 1200€",
    description: "Alpha luxury! Premium designer komadi i dodaci.",
    includes: ["Luxury watch", "Designer clothing", "Accessories", "Grooming kit", "VIP items"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-50-50-burberry",
    name: "50-50 Burberry",
    slug: "50-50-burberry",
    category: "clothing",
    price: 300,
    originalPrice: 750,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#A0522D", // Sienna for Burberry classic check
    rating: 5.0,
    reviews: 145,
    stock: 3,
    potentialValue: "Do 1500€",
    description: "50% šansa za Burberry! Legendarni trench ili dodaci.",
    includes: ["Burberry trench/scarf", "Accessories", "Bag", "Premium items", "Certificate"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-armani",
    name: "Armani Box",
    slug: "armani-box",
    category: "clothing",
    price: 75,
    originalPrice: 190,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#808080", // Gray for Armani sophistication
    rating: 4.9,
    reviews: 423,
    stock: 16,
    potentialValue: "Do 400€",
    description: "Italian elegance! Armani parfemi, odjeća i dodaci.",
    includes: ["Armani perfume", "Shirt/polo", "Belt", "Accessories", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-50-50-jacquemus",
    name: "50-50 Jacquemus Box",
    slug: "50-50-jacquemus-box",
    category: "clothing",
    price: 100,
    originalPrice: 270,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FF69B4", // Hot pink for Jacquemus vibrant style
    rating: 4.9,
    reviews: 234,
    stock: 9,
    potentialValue: "Do 550€",
    description: "French fashion! 50% šansa za Jacquemus bag.",
    includes: ["Jacquemus bag/hat", "Accessories", "Sunglasses", "Clothing", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-after-party",
    name: "After Party Box",
    slug: "after-party-box",
    category: "clothing",
    price: 50,
    originalPrice: 130,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FF6347", // Tomato red for party vibes
    rating: 4.8,
    reviews: 567,
    stock: 24,
    potentialValue: "Do 240€",
    description: "Party outfit! Clubbing odjeća i dodaci.",
    includes: ["Party outfit", "Accessories", "Jewelry", "Makeup", "Club essentials"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-rich-kid",
    name: "Rich Kid",
    slug: "rich-kid",
    category: "clothing",
    price: 150,
    originalPrice: 400,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FFD700", // Gold for rich kid luxury
    rating: 5.0,
    reviews: 278,
    stock: 7,
    potentialValue: "Do 800€",
    description: "Young luxury! Designer streetwear za mladu generaciju.",
    includes: ["Designer hoodie", "Sneakers", "Accessories", "Bag", "Premium items"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-lvmh",
    name: "LVMH Box",
    slug: "lvmh-box",
    category: "clothing",
    price: 100,
    originalPrice: 280,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#000080", // Navy blue for LVMH prestige
    rating: 5.0,
    reviews: 389,
    stock: 12,
    potentialValue: "Do 600€",
    description: "Luxury group! Louis Vuitton, Dior, Fendi komadi.",
    includes: ["LVMH brand item", "Accessories", "Perfume", "Bag/wallet", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-arcteryx",
    name: "Arcteryx Box",
    slug: "arcteryx-box",
    category: "clothing",
    price: 75,
    originalPrice: 200,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#008080", // Teal for Arc'teryx technical gear
    rating: 4.9,
    reviews: 345,
    stock: 18,
    potentialValue: "Do 450€",
    description: "Technical fashion! Arc'teryx jakne i outdoor gear.",
    includes: ["Arc jacket/fleece", "Cap", "Backpack", "Accessories", "Tech wear"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-dior",
    name: "Dior Box",
    slug: "dior-box",
    category: "clothing",
    price: 100,
    originalPrice: 270,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#DDA0DD", // Plum for Dior elegance
    rating: 5.0,
    reviews: 567,
    stock: 10,
    potentialValue: "Do 550€",
    description: "French couture! Dior parfemi, makeup i fashion.",
    includes: ["Dior perfume", "Makeup", "Accessories", "Bag", "Luxury item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-gucci-gang",
    name: "Gucci Gang Box",
    slug: "gucci-gang-box",
    category: "clothing",
    price: 75,
    originalPrice: 195,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#B22222", // Firebrick for Gucci boldness
    rating: 4.9,
    reviews: 678,
    stock: 15,
    potentialValue: "Do 420€",
    description: "Italian fashion! Gucci dodaci i streetwear.",
    includes: ["Gucci accessory", "Belt", "Wallet", "Scarf", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-50-50-drip",
    name: "50-50 Drip Box",
    slug: "50-50-drip-box",
    category: "clothing",
    price: 50,
    originalPrice: 140,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FF6347", // Tomato red for vibrant drip
    rating: 4.8,
    reviews: 890,
    stock: 26,
    potentialValue: "Do 300€",
    description: "50% za designer! Street fashion i brand dodaci.",
    includes: ["Designer item", "Accessories", "Jewelry", "Cap", "Surprise luxury"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-yeezy",
    name: "Yeezy Box",
    slug: "yeezy-box",
    category: "clothing",
    price: 50,
    originalPrice: 135,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#778899", // Light slate gray for Yeezy muted tones
    rating: 4.9,
    reviews: 789,
    stock: 19,
    potentialValue: "Do 280€",
    description: "Kanye vision! Yeezy slides, foam runners i apparel.",
    includes: ["Yeezy slides/foam", "Hoodie", "Socks", "Cap", "Merch"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-supreme",
    name: "Supreme Box",
    slug: "supreme-box",
    category: "clothing",
    price: 100,
    originalPrice: 250,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#DC143C", // Crimson red for Supreme boldness
    rating: 5.0,
    reviews: 1234,
    stock: 14,
    potentialValue: "Do 500€",
    description: "Streetwear king! Supreme box logo i kolabs.",
    includes: ["Supreme tee/hoodie", "Accessories", "Stickers", "Bag", "Limited item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-bape",
    name: "Bape Box",
    slug: "bape-box",
    category: "clothing",
    price: 50,
    originalPrice: 130,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FF6347", // Tomato red for Bape camo
    rating: 4.8,
    reviews: 678,
    stock: 21,
    potentialValue: "Do 260€",
    description: "Japanese street! Bape camo, shark hoodie i dodaci.",
    includes: ["Bape tee", "Camo accessories", "Stickers", "Cap", "Merch"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-cp-company",
    name: "CP Company Box",
    slug: "cp-company-box",
    category: "clothing",
    price: 100,
    originalPrice: 260,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#008080", // Teal for CP Company technical look
    rating: 4.9,
    reviews: 234,
    stock: 11,
    potentialValue: "Do 480€",
    description: "Italian sportswear! CP Company goggle jakne.",
    includes: ["CP jacket/shirt", "Accessories", "Cap", "Pants", "Premium item"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-detention",
    name: "Detention Box",
    slug: "detention-box",
    category: "clothing",
    price: 75,
    originalPrice: 180,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#800000", // Maroon for detention/school vibe
    rating: 4.7,
    reviews: 345,
    stock: 17,
    potentialValue: "Do 320€",
    description: "School vibes! Vintage college i prep odjeća.",
    includes: ["College hoodie", "Varsity jacket", "Backpack", "Cap", "Accessories"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-old-money",
    name: "Old Money Box",
    slug: "old-money-box",
    category: "clothing",
    price: 75,
    originalPrice: 190,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#556B2F", // Dark olive green for old money classic
    rating: 5.0,
    reviews: 456,
    stock: 13,
    potentialValue: "Do 400€",
    description: "Classic elegance! Polo, chinos i timeless fashion.",
    includes: ["Polo shirt", "Chinos", "Leather belt", "Loafers", "Accessories"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-corteiz",
    name: "Corteiz Box",
    slug: "corteiz-box",
    category: "clothing",
    price: 50,
    originalPrice: 130,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#000080", // Navy blue for Corteiz urban style
    rating: 4.9,
    reviews: 789,
    stock: 20,
    potentialValue: "Do 250€",
    description: "UK streetwear! Corteiz hoodie i hype clothing.",
    includes: ["Corteiz hoodie/tee", "Cap", "Socks", "Stickers", "Limited merch"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-victorias-secret",
    name: "Victorias Secret Box",
    slug: "victorias-secret-box",
    category: "clothing",
    price: 75,
    originalPrice: 180,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#FF69B4", // Hot pink for Victoria's Secret allure
    rating: 4.8,
    reviews: 1123,
    stock: 25,
    potentialValue: "Do 300€",
    description: "Beauty i lingerie! VS parfemi, odjeća i beauty.",
    includes: ["VS perfume", "Lingerie", "Lotion", "Bag", "Beauty products"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },
  {
    id: "clothing-adidas",
    name: "Adidas Box",
    slug: "adidas-box",
    category: "clothing",
    price: 50,
    originalPrice: 125,
    image: "/images/01K115ABVE7AF4Y2PN3M95P2RS.webp", // Placeholder image replaced
    dominantColor: "#000000", // Black for Adidas iconic look
    rating: 4.7,
    reviews: 934,
    stock: 32,
    potentialValue: "Do 220€",
    description: "Three stripes! Adidas originals i sportswear.",
    includes: ["Adidas hoodie/tee", "Track pants", "Cap", "Socks", "Accessories"],
    gallery: ["/images/01K115ABVE7AF4Y2PN3M95P2RS.webp"],
  },

  // TV CATEGORY (22 products)
  {
    id: "tv-south-park",
    name: "South Park Box",
    slug: "south-park-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/01JPAJ00B9TB144FPJADRAY89V.webp",
    dominantColor: "#87CEEB", // South Park sky blue
    rating: 4.7,
    reviews: 456,
    stock: 22,
    potentialValue: "Do 180€",
    description: "South Park ludnica! Collector's edition s figurama i dodacima.",
    includes: ["Figurice", "Poster", "T-shirt", "Sticker pack", "DVD set"],
    gallery: ["/images/01JPAJ00B9TB144FPJADRAY89V.webp"],
  },
  {
    id: "tv-gangster-movies",
    name: "Gangster Movies Box",
    slug: "gangster-movies-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/01JWGM9R3RFJ9DWX0GKA8GR521.webp",
    dominantColor: "#2F4F4F", // Dark slate gray for gangster vibe
    rating: 4.8,
    reviews: 378,
    stock: 15,
    potentialValue: "Do 200€",
    description: "Mafija kolekcija! Godfather, Scarface i druge klasike.",
    includes: ["Blu-ray kolekcija", "Poster", "Replica props", "Art book", "Keychain"],
    gallery: ["/images/01JWGM9R3RFJ9DWX0GKA8GR521.webp"],
  },
  {
    id: "tv-game-of-thrones",
    name: "Game of Thrones Box",
    slug: "game-of-thrones-box",
    category: "tv",
    price: 75,
    originalPrice: 189,
    image: "/images/got-box.webp",
    dominantColor: "#8B0000", // Dark red for GoT
    rating: 4.9,
    reviews: 1234,
    stock: 18,
    potentialValue: "Do 300€",
    description: "Winter is coming! GoT ultimate fan kolekcija.",
    includes: ["Complete Blu-ray", "House banners", "Figurice", "Art book", "Replica sword"],
    gallery: ["/images/got-box.webp"],
  },
  {
    id: "tv-breaking-bad",
    name: "Breaking Bad Box",
    slug: "breaking-bad-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/breaking-bad-box.webp",
    dominantColor: "#32CD32", // Green for crystal meth theme
    rating: 4.9,
    reviews: 987,
    stock: 20,
    potentialValue: "Do 220€",
    description: "Say my name! Breaking Bad fan essentials.",
    includes: ["Complete series", "Los Pollos Hermanos merch", "Heisenberg hat", "Poster", "Props"],
    gallery: ["/images/breaking-bad-box.webp"],
  },
  {
    id: "tv-stranger-things",
    name: "Stranger Things Box",
    slug: "stranger-things-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/stranger-things-box.webp",
    dominantColor: "#FF0000", // Red for Stranger Things aesthetic
    rating: 4.8,
    reviews: 845,
    stock: 25,
    potentialValue: "Do 200€",
    description: "Upside Down! Stranger Things kolekcija.",
    includes: ["Series Blu-ray", "Demogorgon figura", "Poster set", "T-shirt", "Stickers"],
    gallery: ["/images/stranger-things-box.webp"],
  },
  {
    id: "tv-the-office",
    name: "The Office Box",
    slug: "the-office-box",
    category: "tv",
    price: 50,
    originalPrice: 125,
    image: "/images/the-office-box.webp",
    dominantColor: "#4169E1", // Royal blue for Dunder Mifflin
    rating: 4.7,
    reviews: 756,
    stock: 30,
    potentialValue: "Do 180€",
    description: "That's what she said! The Office ultimate fan pack.",
    includes: ["Complete series", "Dunder Mifflin merch", "Dundie Award", "Mug", "Posters"],
    gallery: ["/images/the-office-box.webp"],
  },
  {
    id: "tv-friends",
    name: "Friends Box",
    slug: "friends-box",
    category: "tv",
    price: 50,
    originalPrice: 130,
    image: "/images/friends-box.webp",
    dominantColor: "#FF6B9D", // Pink for Central Perk theme
    rating: 4.8,
    reviews: 1123,
    stock: 28,
    potentialValue: "Do 190€",
    description: "I'll be there for you! Friends complete collection.",
    includes: ["Complete series", "Central Perk mug", "Poster set", "T-shirt", "Collectibles"],
    gallery: ["/images/friends-box.webp"],
  },
  {
    id: "tv-peaky-blinders",
    name: "Peaky Blinders Box",
    slug: "peaky-blinders-box",
    category: "tv",
    price: 75,
    originalPrice: 180,
    image: "/images/peaky-blinders-box.webp",
    dominantColor: "#2F4F4F", // Dark gray for Peaky aesthetic
    rating: 4.9,
    reviews: 567,
    stock: 16,
    potentialValue: "Do 280€",
    description: "By order of the Peaky Blinders! Gangster collection.",
    includes: ["Complete series", "Flat cap", "Pocket watch", "Whiskey glasses", "Poster"],
    gallery: ["/images/peaky-blinders-box.webp"],
  },
  {
    id: "tv-rick-and-morty",
    name: "Rick and Morty Box",
    slug: "rick-and-morty-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/rick-morty-box.webp",
    dominantColor: "#00CED1", // Cyan for portal theme
    rating: 4.8,
    reviews: 891,
    stock: 24,
    potentialValue: "Do 200€",
    description: "Wubba lubba dub dub! Rick and Morty fan gear.",
    includes: ["Seasons Blu-ray", "Portal gun replica", "Figurice", "T-shirt", "Stickers"],
    gallery: ["/images/rick-morty-box.webp"],
  },
  {
    id: "tv-the-simpsons",
    name: "The Simpsons Box",
    slug: "the-simpsons-box",
    category: "tv",
    price: 50,
    originalPrice: 125,
    image: "/images/simpsons-box.webp",
    dominantColor: "#FFD700", // Yellow for Simpsons theme
    rating: 4.7,
    reviews: 1234,
    stock: 35,
    potentialValue: "Do 180€",
    description: "D'oh! The Simpsons classic collection.",
    includes: ["Episodes collection", "Figurice", "Duff Beer mug", "Poster", "Comics"],
    gallery: ["/images/simpsons-box.webp"],
  },
  {
    id: "tv-the-walking-dead",
    name: "The Walking Dead Box",
    slug: "walking-dead-box",
    category: "tv",
    price: 75,
    originalPrice: 185,
    image: "/images/walking-dead-box.webp",
    dominantColor: "#8B0000", // Dark red for zombie apocalypse
    rating: 4.8,
    reviews: 678,
    stock: 19,
    potentialValue: "Do 270€",
    description: "Survive the apocalypse! TWD collector's edition.",
    includes: ["Complete seasons", "Zombie figurice", "Lucille replica", "Poster", "Art book"],
    gallery: ["/images/walking-dead-box.webp"],
  },
  {
    id: "tv-sherlock",
    name: "Sherlock Box",
    slug: "sherlock-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/sherlock-box.webp",
    dominantColor: "#000080", // Navy for British detective theme
    rating: 4.9,
    reviews: 456,
    stock: 22,
    potentialValue: "Do 210€",
    description: "Elementary! Sherlock Holmes BBC collection.",
    includes: ["Complete series", "Deerstalker hat", "Magnifying glass", "Poster", "Script book"],
    gallery: ["/images/sherlock-box.webp"],
  },
  {
    id: "tv-narcos",
    name: "Narcos Box",
    slug: "narcos-box",
    category: "tv",
    price: 50,
    originalPrice: 130,
    image: "/images/narcos-box.webp",
    dominantColor: "#8B4513", // Saddle brown for cartel theme
    rating: 4.8,
    reviews: 534,
    stock: 20,
    potentialValue: "Do 200€",
    description: "Plata o plomo! Narcos complete collection.",
    includes: ["Complete series", "Escobar poster", "Colombian flag", "T-shirt", "Collectibles"],
    gallery: ["/images/narcos-box.webp"],
  },
  {
    id: "tv-money-heist",
    name: "Money Heist Box",
    slug: "money-heist-box",
    category: "tv",
    price: 75,
    originalPrice: 180,
    image: "/images/money-heist-box.webp",
    dominantColor: "#DC143C", // Crimson for Money Heist masks
    rating: 4.9,
    reviews: 1123,
    stock: 17,
    potentialValue: "Do 280€",
    description: "Bella ciao! La Casa de Papel heist gear.",
    includes: ["Complete seasons", "Dali mask", "Red jumpsuit", "Poster", "Collectibles"],
    gallery: ["/images/money-heist-box.webp"],
  },
  {
    id: "tv-black-mirror",
    name: "Black Mirror Box",
    slug: "black-mirror-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/black-mirror-box.webp",
    dominantColor: "#1C1C1C", // Almost black for dystopian theme
    rating: 4.8,
    reviews: 678,
    stock: 21,
    potentialValue: "Do 200€",
    description: "Tech dystopia! Black Mirror anthology collection.",
    includes: ["Complete episodes", "Art book", "Poster set", "T-shirt", "Stickers"],
    gallery: ["/images/black-mirror-box.webp"],
  },
  {
    id: "tv-westworld",
    name: "Westworld Box",
    slug: "westworld-box",
    category: "tv",
    price: 75,
    originalPrice: 185,
    image: "/images/westworld-box.webp",
    dominantColor: "#8B4513", // Saddle brown for Western theme
    rating: 4.9,
    reviews: 445,
    stock: 14,
    potentialValue: "Do 270€",
    description: "These violent delights! Westworld fan collection.",
    includes: ["Complete seasons", "Host figurice", "Maze puzzle", "Poster", "Art book"],
    gallery: ["/images/westworld-box.webp"],
  },
  {
    id: "tv-squid-game",
    name: "Squid Game Box",
    slug: "squid-game-box",
    category: "tv",
    price: 50,
    originalPrice: 130,
    image: "/images/squid-game-box.webp",
    dominantColor: "#FF1493", // Deep pink for Squid Game aesthetic
    rating: 4.9,
    reviews: 1567,
    stock: 26,
    potentialValue: "Do 210€",
    description: "456! Squid Game survival kit.",
    includes: ["Complete season", "Player tracksuit", "Dalgona candy", "Mask", "Poster"],
    gallery: ["/images/squid-game-box.webp"],
  },
  {
    id: "tv-the-witcher",
    name: "The Witcher Box",
    slug: "witcher-box",
    category: "tv",
    price: 75,
    originalPrice: 180,
    image: "/images/witcher-box.webp",
    dominantColor: "#696969", // Dim gray for Witcher theme
    rating: 4.8,
    reviews: 789,
    stock: 18,
    potentialValue: "Do 280€",
    description: "Toss a coin! The Witcher Netflix collection.",
    includes: ["Complete seasons", "Medallion replica", "Poster", "T-shirt", "Art book"],
    gallery: ["/images/witcher-box.webp"],
  },
  {
    id: "tv-vikings",
    name: "Vikings Box",
    slug: "vikings-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/vikings-box.webp",
    dominantColor: "#4B0082", // Indigo for Norse theme
    rating: 4.8,
    reviews: 567,
    stock: 20,
    potentialValue: "Do 220€",
    description: "Ragnar Lothbrok! Vikings warrior collection.",
    includes: ["Complete series", "Viking helmet replica", "Rune stones", "Poster", "Art book"],
    gallery: ["/images/vikings-box.webp"],
  },
  {
    id: "tv-the-mandalorian",
    name: "The Mandalorian Box",
    slug: "mandalorian-box",
    category: "tv",
    price: 75,
    originalPrice: 185,
    image: "/images/mandalorian-box.webp",
    dominantColor: "#C0C0C0", // Silver for Mandalorian armor
    rating: 5.0,
    reviews: 1890,
    stock: 15,
    potentialValue: "Do 300€",
    description: "This is the way! Mandalorian and Grogu collection.",
    includes: ["Complete seasons", "Baby Yoda plush", "Helmet replica", "Poster", "Art book"],
    gallery: ["/images/mandalorian-box.webp"],
  },
  {
    id: "tv-ozark",
    name: "Ozark Box",
    slug: "ozark-box",
    category: "tv",
    price: 50,
    originalPrice: 130,
    image: "/images/ozark-box.webp",
    dominantColor: "#1C4587", // Dark blue for Ozark noir theme
    rating: 4.9,
    reviews: 456,
    stock: 19,
    potentialValue: "Do 200€",
    description: "Money laundering! Ozark complete collection.",
    includes: ["Complete seasons", "Byrde family poster", "T-shirt", "Stickers", "Art book"],
    gallery: ["/images/ozark-box.webp"],
  },
  {
    id: "tv-the-boys",
    name: "The Boys Box",
    slug: "the-boys-box",
    category: "tv",
    price: 75,
    originalPrice: 180,
    image: "/images/the-boys-box.webp",
    dominantColor: "#FF0000", // Red for The Boys blood and violence
    rating: 4.9,
    reviews: 1012,
    stock: 17,
    potentialValue: "Do 280€",
    description: "Diabolical! The Boys anti-hero collection.",
    includes: ["Complete seasons", "Homelander figurica", "Comic book", "Poster", "T-shirt"],
    gallery: ["/images/the-boys-box.webp"],
  },

  // CARD-GAMES CATEGORY (6 products)
  {
    id: "card-yugioh",
    name: "Yu-Gi-Oh Box",
    slug: "yugioh-box",
    category: "card-games",
    price: 75,
    originalPrice: 189,
    image: "/images/01JT93TBB4Z93JQ4CE7HNZ1D2R.webp",
    dominantColor: "#9C27B0", // Purple for Yu-Gi-Oh
    rating: 4.9,
    reviews: 923,
    stock: 8,
    potentialValue: "Do 350€",
    description: "Duel! Yu-Gi-Oh premium kolekcija s rijetkim kartama i dodacima.",
    includes: ["Booster packs", "Holographic karte", "Playmat", "Deck box", "Sleeves"],
    gallery: ["/images/01JT93TBB4Z93JQ4CE7HNZ1D2R.webp"],
  },
  {
    id: "card-pokemon-insane",
    name: "Pokemon INSANE Box",
    slug: "pokemon-insane-box",
    category: "card-games",
    price: 250,
    originalPrice: 599,
    image: "/images/01HS4KYNEHXY82Y39MANK851HW.webp",
    dominantColor: "#FFCB05", // Pokemon yellow
    rating: 5.0,
    reviews: 234,
    stock: 3,
    potentialValue: "Do 1500€",
    description: "ULTRA RARE! Pokemon kolekcija s holographic i vintage kartama.",
    includes: ["Graded PSA karte", "Elite Trainer Box", "Booster boxes", "Vintage packs", "Charizard šansa"],
    gallery: ["/images/01HS4KYNEHXY82Y39MANK851HW.webp"],
  },
  {
    id: "card-pokemon-ultra",
    name: "Pokemon Ultra Box",
    slug: "pokemon-ultra-box",
    category: "card-games",
    price: 85,
    originalPrice: 219,
    image: "/images/01K4CXHWCZD975G9KD1SC0MNA4.webp",
    dominantColor: "#3B4CCA", // Pokemon blue
    rating: 4.9,
    reviews: 1234,
    stock: 8,
    potentialValue: "Do 400€",
    description: "Premium Pokemon kolekcija s rijetkim booster packovima.",
    includes: ["Booster box", "Elite trainer box", "Promo cards", "Sleeves", "Playmat"],
    gallery: ["/images/01K4CXHWCZD975G9KD1SC0MNA4.webp"],
  },
  {
    id: "card-pokemon-booster",
    name: "Pokemon Booster Box",
    slug: "pokemon-booster-box",
    category: "card-games",
    price: 35,
    originalPrice: 89,
    image: "/images/01K4CXHJEQ2XTYM2NW7A1HTAKV.webp",
    dominantColor: "#EE1515", // Pokemon red
    rating: 4.7,
    reviews: 2345,
    stock: 45,
    potentialValue: "Do 150€",
    description: "Pokemon booster pack bonanza! Novi setovi i promo karte.",
    includes: ["Booster packs", "Promo card", "Coin", "Stickers", "Code cards"],
    gallery: ["/images/01K4CXHJEQ2XTYM2NW7A1HTAKV.webp"],
  },
  {
    id: "card-pokemon-deluxe",
    name: "Pokemon Deluxe Box",
    slug: "pokemon-deluxe-box",
    category: "card-games",
    price: 50,
    originalPrice: 129,
    image: "/images/01HS4M2XHNSV6PQP343MG7JQ35.webp",
    dominantColor: "#FF6347", // Tomato red for Deluxe
    rating: 4.8,
    reviews: 1567,
    stock: 23,
    potentialValue: "Do 220€",
    description: "Deluxe Pokemon paket! Trading cards i gaming dodaci.",
    includes: ["Elite trainer box", "Tin box", "Sleeves", "Playmat", "Dice set"],
    gallery: ["/images/01HS4M2XHNSV6PQP343MG7JQ35.webp"],
  },
  {
    id: "card-magic-gathering",
    name: "Magic: The Gathering Box",
    slug: "magic-gathering-box",
    category: "card-games",
    price: 100,
    originalPrice: 250,
    image: "/images/magic-gathering-box.webp",
    dominantColor: "#FF8C00", // Dark orange for Magic
    rating: 4.9,
    reviews: 678,
    stock: 12,
    potentialValue: "Do 500€",
    description: "MTG ultimate! Booster boxes i rare cards.",
    includes: ["Booster box", "Mythic rare cards", "Playmat", "Deck box", "Sleeves"],
    gallery: ["/images/magic-gathering-box.webp"],
  },
]

export function getProductsByCategory(categoryId: string) {
  return products.filter((p) => p.category === categoryId)
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug || p.id === slug)
}

export function getCategoryById(categoryId: string) {
  return categories.find((c) => c.id === categoryId)
}
