export const categories = [
  { id: "games", name: "Igre", icon: "🎮", description: "Video igre i gaming oprema", glowColor: "#a855f7" },
  { id: "gaming", name: "Gaming", icon: "🕹️", description: "Gaming oprema i periferija", glowColor: "#ec4899" },
  { id: "tech", name: "Tech", icon: "💻", description: "Tehnologija i gadgeti", glowColor: "#3b82f6" },
  {
    id: "card-games",
    name: "Kartaške Igre",
    icon: "🃏",
    description: "Kolekcionarske i kartaške igre",
    glowColor: "#f59e0b",
  },
  { id: "tv", name: "TV", icon: "📺", description: "TV i streaming paketi", glowColor: "#ef4444" },
  { id: "sport", name: "Sport", icon: "⚽", description: "Sportska oprema i dodaci", glowColor: "#22c55e" },
  { id: "perfume", name: "Parfemi", icon: "🌸", description: "Luksuzni mirisi", glowColor: "#f472b6" },
  { id: "car", name: "Auto", icon: "🚗", description: "Auto oprema i dodaci", glowColor: "#64748b" },
  { id: "clothing", name: "Odjeća", icon: "👕", description: "Moda i odjeća", glowColor: "#8b5cf6" },
  { id: "shoes", name: "Obuća", icon: "👟", description: "Cipele i tenisice", glowColor: "#06b6d4" },
  { id: "sweets", name: "Slatkiši", icon: "🍬", description: "Slatke poslastice", glowColor: "#f97316" },
  { id: "home", name: "Dom", icon: "🏠", description: "Proizvodi za dom", glowColor: "#84cc16" },
  { id: "beach", name: "Plaža", icon: "🏖️", description: "Oprema za plažu i ljeto", glowColor: "#fbbf24" },
  { id: "jewelry", name: "Nakit", icon: "💎", description: "Luksuzni nakit i satovi", glowColor: "#c084fc" },
  { id: "gift-card", name: "Poklon Kartice", icon: "🎁", description: "Poklon bonovi i kartice", glowColor: "#fb7185" },
  { id: "music", name: "Glazba", icon: "🎵", description: "Glazbena oprema i instrumenti", glowColor: "#14b8a6" },
  { id: "bag", name: "Torbe", icon: "👜", description: "Torbe i ruksaci", glowColor: "#a78bfa" },
  { id: "watch", name: "Satovi", icon: "⌚", description: "Ručni satovi i pametni satovi", glowColor: "#60a5fa" },
]

export const products = [
  // SPORT CATEGORY (24 products)
  {
    id: "sport-fcb-lover",
    name: "FCB Lover Box",
    slug: "fcb-lover-box",
    category: "sport",
    price: 50,
    originalPrice: 120,
    image: "/images/01K1159R2V46DSP6851VG3WXQK.webp",
    rating: 4.8,
    reviews: 342,
    stock: 25,
    potentialValue: "Do 180€",
    description: "Sve za Barcelona fanove! Dres, šal i ekskluzivni FCB merchandise.",
    includes: ["FCB dres", "Navijački šal", "Zastava", "Kapa", "Bedž kolekcija"],
  },
  {
    id: "sport-basket",
    name: "Basket Box",
    slug: "basket-box",
    category: "sport",
    price: 50,
    originalPrice: 130,
    image: "/images/01J8CWHXD96R3Q61XRS4Q0PSWP.webp",
    rating: 4.7,
    reviews: 289,
    stock: 30,
    potentialValue: "Do 200€",
    description: "Košarkaški set! NBA merchandise, lopta i oprema.",
    includes: ["Košarkaška lopta", "NBA dres", "Ručnik", "Narukvica", "Čarape"],
  },
  {
    id: "sport-baseball-100",
    name: "Baseball 100% Box",
    slug: "baseball-100-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01J8CWG61W16RP1ZAA0JJYJQ02.webp",
    rating: 4.9,
    reviews: 156,
    stock: 18,
    potentialValue: "Do 250€",
    description: "Profesionalni baseball set! Rukavica, lopta i MLB memorabilije.",
    includes: ["Baseball rukavica", "Službena lopta", "MLB kapa", "Bejzbol majica", "Autogram poster"],
  },
  {
    id: "sport-real",
    name: "Real Box",
    slug: "real-box",
    category: "sport",
    price: 50,
    originalPrice: 115,
    image: "/images/01K1159NTHVJW6317M8M8EJ95T.webp",
    rating: 4.8,
    reviews: 421,
    stock: 28,
    potentialValue: "Do 170€",
    description: "Hala Madrid! Real Madrid merchandise i navijačka oprema.",
    includes: ["Real Madrid dres", "Šal", "Privjesci", "Poster set", "Bedž kolekcija"],
  },
  {
    id: "sport-touchdown",
    name: "Touchdown Box",
    slug: "touchdown-box",
    category: "sport",
    price: 90,
    originalPrice: 220,
    image: "/images/01J8CWKDKM3VF0MXW3XGT9X864.webp",
    rating: 4.9,
    reviews: 187,
    stock: 15,
    potentialValue: "Do 300€",
    description: "NFL excitement! Američki nogomet oprema i NFL merchandise.",
    includes: ["NFL dres", "Američka lopta", "Kaciga mini", "Rukavice", "Team flag"],
  },
  {
    id: "sport-manchester-city",
    name: "Manchester City Box",
    slug: "manchester-city-box",
    category: "sport",
    price: 50,
    originalPrice: 125,
    image: "/images/01K1159HBN6EYMD1T7J1XJB1MZ.webp",
    rating: 4.7,
    reviews: 345,
    stock: 32,
    potentialValue: "Do 190€",
    description: "Citizens pride! Manchester City dres i navijačka kolekcija.",
    includes: ["Man City dres", "Šal", "Kapa", "Bedž set", "Narukvica"],
  },
  {
    id: "sport-ufc-fighter",
    name: "UFC Fighter Box",
    slug: "ufc-fighter-box",
    category: "sport",
    price: 75,
    originalPrice: 175,
    image: "/images/01HVC94BETCTB16E49S672YKRY.webp",
    rating: 4.8,
    reviews: 234,
    stock: 20,
    potentialValue: "Do 260€",
    description: "Fight gear! UFC oprema za treninge i borbe.",
    includes: ["MMA rukavice", "Bandaže", "Majica", "Šorts", "Trening oprema"],
  },
  {
    id: "sport-golf",
    name: "Golf Box",
    slug: "golf-box",
    category: "sport",
    price: 75,
    originalPrice: 190,
    image: "/images/01J8CWMYAV86A5FRJ1E4Y9V30C.webp",
    rating: 4.6,
    reviews: 128,
    stock: 22,
    potentialValue: "Do 280€",
    description: "Gentleman's sport! Golf oprema i dodaci za savršen swing.",
    includes: ["Golf rukavice", "Lopte set", "Tee set", "Kapa", "Ručnik"],
  },
  {
    id: "sport-rugby-love",
    name: "Rugby Love Box",
    slug: "rugby-love-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01JN6CY10CPE3FWADRTB8A501K.webp",
    rating: 4.7,
    reviews: 167,
    stock: 19,
    potentialValue: "Do 250€",
    description: "Rough and tough! Rugby oprema i international merchandise.",
    includes: ["Rugby lopta", "Dres", "Zaštitna oprema", "Čarape", "Trening dodaci"],
  },
  {
    id: "sport-mix",
    name: "Sport Mix Box",
    slug: "sport-mix-box",
    category: "sport",
    price: 100,
    originalPrice: 250,
    image: "/images/01J3CY0GSJ3KNE28HDZ09YN1J0.webp",
    rating: 4.9,
    reviews: 456,
    stock: 12,
    potentialValue: "Do 400€",
    description: "Najbolje od svega! Mix sportske opreme iz raznih sportova.",
    includes: ["Multi-sport oprema", "Brendirana odjeća", "Lopte", "Dodaci", "Surprise items"],
  },
  {
    id: "sport-padel-ace",
    name: "Padel Ace Box",
    slug: "padel-ace-box",
    category: "sport",
    price: 75,
    originalPrice: 185,
    image: "/images/01JN6CY72MWF0PHKY5MWV8K561.webp",
    rating: 4.8,
    reviews: 198,
    stock: 16,
    potentialValue: "Do 270€",
    description: "Padel revolution! Oprema za najbrže rastući sport.",
    includes: ["Padel lopte", "Grip tape", "Rukavice", "Majica", "Torba"],
  },
  {
    id: "sport-checkmate",
    name: "Checkmate Box",
    slug: "checkmate-box",
    category: "sport",
    price: 50,
    originalPrice: 120,
    image: "/images/01JEYJBGWMH92NRQ2F7M5PRNSG.webp",
    rating: 4.5,
    reviews: 234,
    stock: 35,
    potentialValue: "Do 160€",
    description: "Šah je sport uma! Profesionalne figure i šahovska oprema.",
    includes: ["Šahovska ploča", "Figure set", "Šahovski sat", "Knjiga", "Torba za figure"],
  },
  {
    id: "sport-bayern",
    name: "Bayern Box",
    slug: "bayern-box",
    category: "sport",
    price: 50,
    originalPrice: 125,
    image: "/images/01K1159KMJ0N80W96EWHP2AHM6.webp",
    rating: 4.9,
    reviews: 389,
    stock: 24,
    potentialValue: "Do 185€",
    description: "Mia san mia! Bayern Munich official merchandise.",
    includes: ["Bayern dres", "Šal", "Kapa", "Bedž set", "Zastava"],
  },
  {
    id: "sport-sparring",
    name: "Sparring Box",
    slug: "sparring-box",
    category: "sport",
    price: 75,
    originalPrice: 175,
    image: "/images/01J1SGFDFY5Z6HGD47HKWWHC1N.webp",
    rating: 4.7,
    reviews: 267,
    stock: 21,
    potentialValue: "Do 240€",
    description: "Boksačka oprema! Sve za trening i sparring.",
    includes: ["Boksačke rukavice", "Bandaže", "Zaštitnik zubi", "Trening torba", "Oprema"],
  },
  {
    id: "sport-euro",
    name: "Euro Box",
    slug: "euro-box",
    category: "sport",
    price: 100,
    originalPrice: 240,
    image: "/images/01J09RAYHE1MZZC7AFMZT7KEZ3.webp",
    rating: 4.9,
    reviews: 512,
    stock: 10,
    potentialValue: "Do 350€",
    description: "European football! Najbolje od EURO turnira.",
    includes: ["Službena lopta", "Multi dres", "Šalovi", "Memorabilije", "VIP dodaci"],
  },
  {
    id: "sport-football-lover",
    name: "Football Lover",
    slug: "football-lover",
    category: "sport",
    price: 50,
    originalPrice: 130,
    image: "/images/01HNCX89C1AP1NDM0GD4X4FCG9.webp",
    rating: 4.8,
    reviews: 678,
    stock: 40,
    potentialValue: "Do 200€",
    description: "Za prave ljubitelje nogometa! Oprema i fan merchandise.",
    includes: ["Nogometna lopta", "Dres", "Šal", "Čarape", "Trening dodaci"],
  },
  {
    id: "sport-ride-n-slide",
    name: "Ride n Slide Box",
    slug: "ride-n-slide-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01JC5YBT3521YGHF7GV6HC97VW.webp",
    rating: 4.6,
    reviews: 189,
    stock: 17,
    potentialValue: "Do 260€",
    description: "Skate and surf! Oprema za ekstremne sportove.",
    includes: ["Skateboard dodaci", "Zaštitna oprema", "Majica", "Naljepnice", "Grip tape"],
  },
  {
    id: "sport-mountain-rider",
    name: "Mountain Rider Box",
    slug: "mountain-rider-box",
    category: "sport",
    price: 100,
    originalPrice: 250,
    image: "/images/01JFG28H45890ANCT44P1E0ED2.webp",
    rating: 4.9,
    reviews: 234,
    stock: 14,
    potentialValue: "Do 380€",
    description: "MTB adventure! Mountain bike oprema i dodaci.",
    includes: ["Bike dodaci", "Zaštitna oprema", "Rukavice", "Boca", "Tools set"],
  },
  {
    id: "sport-rock-ride",
    name: "Rock Ride Box",
    slug: "rock-ride-box",
    category: "sport",
    price: 75,
    originalPrice: 185,
    image: "/images/01JC5NSMP8PW0KPEKF0073SX21.webp",
    rating: 4.7,
    reviews: 156,
    stock: 19,
    potentialValue: "Do 270€",
    description: "Climbing gear! Oprema za penjanje i bouldering.",
    includes: ["Penjačke rukavice", "Chalk bag", "Karabiner set", "Majica", "Dodaci"],
  },
  {
    id: "sport-fit-fury",
    name: "Fit Fury Box",
    slug: "fit-fury-box",
    category: "sport",
    price: 50,
    originalPrice: 125,
    image: "/images/01JN6CY3YG68SCQ4QWDJZXEQ2Q.webp",
    rating: 4.8,
    reviews: 445,
    stock: 33,
    potentialValue: "Do 190€",
    description: "Fitness revolution! Gym oprema i dodaci za trening.",
    includes: ["Resistance bands", "Rukavice", "Boca", "Ručnik", "Suplementi"],
  },
  {
    id: "sport-psg-pro",
    name: "PSG Pro Box",
    slug: "psg-pro-box",
    category: "sport",
    price: 50,
    originalPrice: 120,
    image: "/images/01K1159TXMJH8ARSKG7NNAD73Y.webp",
    rating: 4.9,
    reviews: 567,
    stock: 26,
    potentialValue: "Do 180€",
    description: "Ici c'est Paris! PSG official merchandise i navijačka oprema.",
    includes: ["PSG dres", "Šal", "Kapa", "Bedž kolekcija", "Poster"],
  },
  {
    id: "sport-athletic",
    name: "Athletic Box",
    slug: "athletic-box",
    category: "sport",
    price: 35,
    originalPrice: 85,
    image: "/images/01HPGXQD96PD4VJHA84KBE60GE.webp",
    rating: 4.6,
    reviews: 289,
    stock: 45,
    potentialValue: "Do 140€",
    description: "Atletika oprema! Sve za trčanje i atletske discipline.",
    includes: ["Running majica", "Čarape", "Traka za glavu", "Boca", "Timing watch"],
  },
  {
    id: "sport-tennis",
    name: "Tennis Box",
    slug: "tennis-box",
    category: "sport",
    price: 75,
    originalPrice: 180,
    image: "/images/01JN6CXV3ETN4MMZKKQ7FRYRCS.webp",
    rating: 4.7,
    reviews: 198,
    stock: 20,
    potentialValue: "Do 250€",
    description: "Game, set, match! Teniski set i profesionalna oprema.",
    includes: ["Tenis lopte", "Grip tape", "Znojnica", "Torba", "Ručnik"],
  },

  // PERFUME CATEGORY (2 products)
  {
    id: "perfume-box",
    name: "Perfume Box",
    slug: "perfume-box",
    category: "perfume",
    price: 50,
    originalPrice: 140,
    image: "/images/01JRMPW8V0MFRW5NA1RG94CGD1.webp",
    rating: 4.8,
    reviews: 892,
    stock: 35,
    potentialValue: "Do 250€",
    description: "Luksuzni mirisi! Designer parfemi i niche fragrances.",
    includes: ["Parfem 50ml+", "Travel size", "Cologne", "Samples set", "Giftbox"],
  },
  {
    id: "perfume-rituals",
    name: "Rituals Box",
    slug: "rituals-box",
    category: "perfume",
    price: 75,
    originalPrice: 180,
    image: "/images/01JNRFA9YJ7FJFFGD48SJJE1QJ.webp",
    rating: 4.9,
    reviews: 567,
    stock: 22,
    potentialValue: "Do 280€",
    description: "Wellness rituali! Rituals proizvodi za njegu i mirise.",
    includes: ["Body cream", "Shower gel", "Parfem", "Świeca", "Gift set"],
  },

  // SHOES CATEGORY (7 products)
  {
    id: "shoes-dunk-dream",
    name: "Dunk Dream Box",
    slug: "dunk-dream-box",
    category: "shoes",
    price: 75,
    originalPrice: 200,
    image: "/Images/01HNDH7QRZGWTWZ1WQAXNM0XHP.webp",
    rating: 4.9,
    reviews: 678,
    stock: 15,
    potentialValue: "Do 350€",
    description: "Nike Dunk kolekcija! Limitirane Dunk tenisice i dodaci.",
    includes: ["Nike Dunk", "Crep protect", "Laces set", "Stickers", "Box"],
  },
  {
    id: "shoes-sneakers-drip",
    name: "Sneakers Drip",
    slug: "sneakers-drip",
    category: "shoes",
    price: 75,
    originalPrice: 185,
    image: "/images/01HNCWBMYMCQBPB72FZFEE01NC.webp",
    rating: 4.8,
    reviews: 543,
    stock: 18,
    potentialValue: "Do 320€",
    description: "Sneaker game! Retro i moderne tenisice.",
    includes: ["Branded sneakers", "Čistač", "Extra laces", "Shoe horn", "Bag"],
  },
  {
    id: "shoes-jordans",
    name: "Jordans Box",
    slug: "jordans-box",
    category: "shoes",
    price: 75,
    originalPrice: 195,
    image: "/images/01K2PH91T089TBK5YSF5P6H3R1.webp",
    rating: 4.9,
    reviews: 834,
    stock: 12,
    potentialValue: "Do 400€",
    description: "Jumpman legacy! Air Jordan tenisice i merchandise.",
    includes: ["Air Jordan", "Jordan majica", "Caps", "Socks", "Keychain"],
  },
  {
    id: "shoes-la-flame",
    name: "La Flame Box",
    slug: "la-flame-box",
    category: "shoes",
    price: 100,
    originalPrice: 260,
    image: "/images/01HND7FHPVFHKY7RCHB9XM1JYM.webp",
    rating: 4.9,
    reviews: 456,
    stock: 8,
    potentialValue: "Do 500€",
    description: "Travis Scott kolabs! Cactus Jack tenisice i merch.",
    includes: ["Travis collab shoes", "Hoodie", "Vinyl", "Poster", "Stickers"],
  },
  {
    id: "shoes-dunks-lover",
    name: "Dunks Lover",
    slug: "dunks-lover",
    category: "shoes",
    price: 150,
    originalPrice: 400,
    image: "/images/01HS6MBE697BFSB2VX7FDV3J9F.webp",
    rating: 5.0,
    reviews: 234,
    stock: 5,
    potentialValue: "Do 800€",
    description: "Premium Dunk! Rijetke i limitirane Nike Dunk tenisice.",
    includes: ["Rare Dunks", "Premium box", "Certificate", "Cleaning kit", "Display stand"],
  },
  {
    id: "shoes-subscription",
    name: "Shoes Subscription Box",
    slug: "shoes-subscription-box",
    category: "shoes",
    price: 50,
    originalPrice: 130,
    image: "/images/01HNCWA365FN0EK2PQFMS1E734.webp",
    rating: 4.7,
    reviews: 389,
    stock: 28,
    potentialValue: "Do 220€",
    description: "Mjesečno iznenađenje! Subscription box s tenisicama.",
    includes: ["Branded shoes", "Accessories", "Socks", "Care kit", "Surprise items"],
  },
  {
    id: "shoes-step-up",
    name: "Step Up Box",
    slug: "step-up-box",
    category: "shoes",
    price: 75,
    originalPrice: 180,
    image: "/images/01HNDBSSDXQMX0TSXGC46H4ZMR.webp",
    rating: 4.8,
    reviews: 467,
    stock: 20,
    potentialValue: "Do 300€",
    description: "Lifestyle footwear! Casual i street style tenisice.",
    includes: ["Lifestyle shoes", "Insoles", "Laces pack", "Cleaner", "Bag"],
  },

  // SWEETS CATEGORY (1 product)
  {
    id: "sweets-surprise",
    name: "Sweet Surprise Box",
    slug: "sweet-surprise-box",
    category: "sweets",
    price: 20,
    originalPrice: 50,
    image: "/images/01KB530GDAPH6DVN62K7TT06MK.webp",
    rating: 4.9,
    reviews: 1234,
    stock: 89,
    potentialValue: "Do 80€",
    description: "Slatkiši iz cijelog svijeta! Candy, čokolade i poslastice.",
    includes: ["Import candy", "Čokolade", "Gumeni bomboni", "Snacks", "Surprise treat"],
  },

  // HOME CATEGORY (6 products)
  {
    id: "home-vintage-treasures",
    name: "Vintage Treasures",
    slug: "vintage-treasures",
    category: "home",
    price: 50,
    originalPrice: 130,
    image: "/images/01KDDWZ5SHK63F2JEGBNQREHK9.webp",
    rating: 4.7,
    reviews: 234,
    stock: 18,
    potentialValue: "Do 220€",
    description: "Vintage dekor! Retro predmeti za dom.",
    includes: ["Vintage dekor", "Retro poster", "Svijeća", "Ukras", "Collectibles"],
  },
  {
    id: "home-luxury",
    name: "Home Luxury Box",
    slug: "home-luxury-box",
    category: "home",
    price: 75,
    originalPrice: 190,
    image: "/images/01KBPZEMQG0SM2376QJH82SQCB.webp",
    rating: 4.9,
    reviews: 456,
    stock: 14,
    potentialValue: "Do 300€",
    description: "Luksuz za dom! Premium predmeti i dekoracije.",
    includes: ["Luxury dekor", "Svijeće", "Diffuser", "Throw blanket", "Premium ukras"],
  },
  {
    id: "home-design",
    name: "Home Design Box",
    slug: "home-design-box",
    category: "home",
    price: 75,
    originalPrice: 185,
    image: "/images/01HWD335QCGV3WGMF299TXNPJH.webp",
    rating: 4.8,
    reviews: 378,
    stock: 16,
    potentialValue: "Do 280€",
    description: "Designer komadi! Moderni predmeti za uređenje doma.",
    includes: ["Design lighting", "Wall art", "Dekor", "Tekstil", "Modern pieces"],
  },
  {
    id: "home-grill-master",
    name: "Grill Master Box",
    slug: "grill-master-box",
    category: "home",
    price: 100,
    originalPrice: 250,
    image: "/images/01JZWDP0H67BQYTYY71AGTC6SW.webp",
    rating: 4.9,
    reviews: 567,
    stock: 12,
    potentialValue: "Do 400€",
    description: "BBQ essentials! Sve za savršeno roštiljanje.",
    includes: ["Grill tools set", "Spices", "Apron", "Termometar", "Cleaning kit"],
  },
  {
    id: "home-box",
    name: "Home Box",
    slug: "home-box",
    category: "home",
    price: 50,
    originalPrice: 125,
    image: "/images/01HQJ8WCKMJB52KCMCA4XHE68A.webp",
    rating: 4.7,
    reviews: 689,
    stock: 30,
    potentialValue: "Do 200€",
    description: "Praktični predmeti za dom! Kuhinja, kupaonica, dnevni boravak.",
    includes: ["Kitchen gadgets", "Dekor", "Tekstil", "Organizatori", "Useful items"],
  },
  {
    id: "home-magic-night",
    name: "Magic Night Box",
    slug: "magic-night-box",
    category: "home",
    price: 50,
    originalPrice: 135,
    image: "/images/01KD0T4WX80C1AZM6M9MN5RB16 (1).webp",
    rating: 4.8,
    reviews: 445,
    stock: 22,
    potentialValue: "Do 210€",
    description: "Romantična atmosfera! LED rasvjeta i ambient lighting.",
    includes: ["LED lights", "Svijeće", "Diffuser", "Soft blanket", "Mood lighting"],
  },

  // CAR CATEGORY (5 products)
  {
    id: "car-50-50-bikes",
    name: "50-50 Bikes",
    slug: "50-50-bikes",
    category: "car",
    price: 650,
    originalPrice: 1500,
    image: "/images/01JVY8E72R8GET3JF1EHH5CVPF.webp",
    rating: 5.0,
    reviews: 89,
    stock: 3,
    potentialValue: "Do 3000€",
    description: "50% šansa za high-end bicikl! Premium cycling oprema.",
    includes: ["Premium bike / accessories", "Helmet", "Gear", "Maintenance kit", "Cycling wear"],
  },
  {
    id: "car-suzukis-obsession",
    name: "Suzukis Obsession",
    slug: "suzukis-obsession",
    category: "car",
    price: 650,
    originalPrice: 1600,
    image: "/images/01JYS09H8NYBT88DE32NANMDWP.webp",
    rating: 4.9,
    reviews: 67,
    stock: 2,
    potentialValue: "Do 3500€",
    description: "Suzuki fanovi! Motor oprema i Suzuki merchandise.",
    includes: ["Suzuki gear", "Riding equipment", "Merch", "Accessories", "Premium items"],
  },
  {
    id: "car-yamaha-madness",
    name: "Yamaha Madness Box",
    slug: "yamaha-madness-box",
    category: "car",
    price: 650,
    originalPrice: 1550,
    image: "/images/01JYRZZGNK98GPWHSE4VC8FZQW.webp",
    rating: 5.0,
    reviews: 78,
    stock: 2,
    potentialValue: "Do 3200€",
    description: "Yamaha passion! Motor oprema i Yamaha exclusive gear.",
    includes: ["Yamaha equipment", "Riding gear", "Helmet", "Gloves", "Premium merch"],
  },
  {
    id: "car-automotive-elite",
    name: "Automotive Elite",
    slug: "automotive-elite",
    category: "car",
    price: 50,
    originalPrice: 130,
    image: "/images/01KDDWWJQZVY5GAS9E1VTVEXCC.webp",
    rating: 4.8,
    reviews: 345,
    stock: 25,
    potentialValue: "Do 220€",
    description: "Auto dodaci! Premium car accessories i gadgeti.",
    includes: ["Car gadgets", "Air freshener", "Phone holder", "Cleaning kit", "LED lights"],
  },
  {
    id: "car-bikers-bounty",
    name: "Bikers Bounty Box",
    slug: "bikers-bounty-box",
    category: "car",
    price: 75,
    originalPrice: 180,
    image: "/images/01HNCXBGTGBAPR0DQDM9NY4FB4.webp",
    rating: 4.9,
    reviews: 234,
    stock: 18,
    potentialValue: "Do 300€",
    description: "Biker lifestyle! Motorističke rukavice, oprema i dodaci.",
    includes: ["Riding gloves", "Balaclava", "Chain cleaner", "Tools", "Merch"],
  },

  // MUSIC CATEGORY (5 products)
  {
    id: "music-rock-with-you",
    name: "Rock with You Box",
    slug: "rock-with-you-box",
    category: "music",
    price: 50,
    originalPrice: 125,
    image: "/images/01JMM9AP625APC6P9VQG2Q10TJ.webp",
    rating: 4.8,
    reviews: 456,
    stock: 28,
    potentialValue: "Do 200€",
    description: "Rock legends! Band merchandise, vinyl i rock memorabilije.",
    includes: ["Band merch", "Vinyl record", "Poster", "Pick set", "Strings"],
  },
  {
    id: "music-vinyl-vibes",
    name: "Vinyl Vibes",
    slug: "vinyl-vibes",
    category: "music",
    price: 75,
    originalPrice: 180,
    image: "/images/01KAK6HFWE9SRGW3X5AWTAKBXR.webp",
    rating: 4.9,
    reviews: 567,
    stock: 15,
    potentialValue: "Do 280€",
    description: "Vinyl kolekcija! Klasični albumi na vinilu.",
    includes: ["Vinyl records", "Cleaning kit", "Storage", "Sleeve protectors", "Rare album"],
  },
  {
    id: "music-king-of-pop",
    name: "King of the Pop Box",
    slug: "king-of-pop-box",
    category: "music",
    price: 100,
    originalPrice: 250,
    image: "/images/01JMM9AKZEZ7MRJX8NKGVCB7PC.webp",
    rating: 5.0,
    reviews: 789,
    stock: 10,
    potentialValue: "Do 400€",
    description: "MJ tribute! Michael Jackson memorabilije i kolekcionarski predmeti.",
    includes: ["MJ vinyl", "Poster set", "Merch", "Collectibles", "Rare items"],
  },
  {
    id: "music-hip-hop-classic",
    name: "Hip Hop Classic Box",
    slug: "hip-hop-classic-box",
    category: "music",
    price: 75,
    originalPrice: 185,
    image: "/images/01JMM9AHQ0JE5Y6SNMDRKEG9DG.webp",
    rating: 4.9,
    reviews: 678,
    stock: 18,
    potentialValue: "Do 300€",
    description: "90s hip hop! Classic rap vinyl i street wear.",
    includes: ["Hip hop vinyl", "Snapback", "Merch", "Poster", "Stickers"],
  },
  {
    id: "music-maestro",
    name: "The Maestro Box",
    slug: "maestro-box",
    category: "music",
    price: 100,
    originalPrice: 240,
    image: "/images/01JMMBRVMR27E159BE9SVHAG54.webp",
    rating: 4.8,
    reviews: 234,
    stock: 12,
    potentialValue: "Do 380€",
    description: "Klasična glazba! Orkestarske partiture i classical vinyl.",
    includes: ["Classical vinyl", "Sheet music", "Conductor baton", "Books", "Premium items"],
  },

  // CLOTHING CATEGORY (30 products)
  {
    id: "Business-Man-Box",
    name: "Business Man Box",
    slug: "Business-Man-Box",
    category: "clothing",
    price: 75,
    originalPrice: 260,
    image: "/images/01JRMPTJ3BM3857DQ008HXFXFZ.webp",
    rating: 4.9,
    reviews: 345,
    stock: 15,
    potentialValue: "Do 450€",
    description: "Business luksuz! Premium odijela, košulje i dodaci.",
    includes: ["Designer shirt", "Tie", "Cufflinks", "Belt", "Luxury accessories"],
  },
  {
    id: "clothing-executive-ceo",
    name: "Executive CEO Box",
    slug: "executive-ceo-box",
    category: "clothing",
    price: 100,
    originalPrice: 260,
    image: "/images/01KBPZEGFQ0XYXPJ9TE4GC175F.webp",
    rating: 4.9,
    reviews: 345,
    stock: 15,
    potentialValue: "Do 450€",
    description: "Business luksuz! Premium odijela, košulje i dodaci.",
    includes: ["Designer shirt", "Tie", "Cufflinks", "Belt", "Luxury accessories"],
  },
  {
    id: "clothing-balenciaga-prada",
    name: "Balenciaga X Prada Box",
    slug: "balenciaga-prada-box",
    category: "clothing",
    price: 100,
    originalPrice: 280,
    image: "/images/01HZSKY831KD0XY5YJGPVD66DY.webp",
    rating: 5.0,
    reviews: 234,
    stock: 8,
    potentialValue: "Do 600€",
    description: "High fashion! Balenciaga i Prada komadi i dodaci.",
    includes: ["Designer piece", "Accessories", "Bag", "Sunglasses", "Premium item"],
  },
  {
    id: "clothing-chrome-hearts",
    name: "Chrome Hearts Box",
    slug: "chrome-hearts-box",
    category: "clothing",
    price: 75,
    originalPrice: 190,
    image: "/images/01JPWBVH3YP9W66N6NPMJ1YDEC.webp",
    rating: 4.9,
    reviews: 456,
    stock: 12,
    potentialValue: "Do 400€",
    description: "Rock luxury! Chrome Hearts nakit i odjeća.",
    includes: ["CH jewelry", "T-shirt", "Accessories", "Ring", "Premium items"],
  },
  {
    id: "clothing-chanel",
    name: "Chanel Box",
    slug: "chanel-box",
    category: "clothing",
    price: 100,
    originalPrice: 270,
    image: "/images/01JDA4JB2PV881R5F9JQ5WGJ0S.webp",
    rating: 5.0,
    reviews: 567,
    stock: 10,
    potentialValue: "Do 550€",
    description: "Iconic elegance! Chanel parfemi, dodaci i odjeća.",
    includes: ["Chanel perfume", "Accessories", "Makeup", "Bag", "Luxury item"],
  },
  {
    id: "clothing-celine",
    name: "Celine Box",
    slug: "celine-box",
    category: "clothing",
    price: 75,
    originalPrice: 185,
    image: "/images/01JSPDCJQ94XP8Y7X8TKV7TM93.webp",
    rating: 4.8,
    reviews: 289,
    stock: 14,
    potentialValue: "Do 380€",
    description: "Parisian chic! Celine torbe i fashion dodaci.",
    includes: ["Celine accessory", "Wallet", "Sunglasses", "Scarf", "Premium item"],
  },
  {
    id: "clothing-palm-angels",
    name: "Palm Angels Box",
    slug: "palm-angels-box",
    category: "clothing",
    price: 50,
    originalPrice: 135,
    image: "/images/01K2PHEASK94TWQK97ZJRBDT35.webp",
    rating: 4.9,
    reviews: 678,
    stock: 22,
    potentialValue: "Do 250€",
    description: "LA streetwear! Palm Angels hoodie, majice i dodaci.",
    includes: ["PA hoodie/tee", "Cap", "Socks", "Stickers", "Accessories"],
  },
  {
    id: "clothing-maison-goyard",
    name: "Maison Goyard Box",
    slug: "maison-goyard-box",
    category: "clothing",
    price: 180,
    originalPrice: 450,
    image: "/images/01JPWBTYZMQWB6HN9781M46DTT.webp",
    rating: 5.0,
    reviews: 123,
    stock: 5,
    potentialValue: "Do 900€",
    description: "French luxury! Goyard torbe i premium dodaci.",
    includes: ["Goyard bag", "Wallet", "Cardholder", "Accessories", "Authentication"],
  },
  {
    id: "clothing-spoiled-wife",
    name: "Spoiled Wife Box",
    slug: "spoiled-wife-box",
    category: "clothing",
    price: 50,
    originalPrice: 140,
    image: "/images/01JM20MPH4AE265H1CEYQNQ7WD.webp",
    rating: 4.8,
    reviews: 890,
    stock: 28,
    potentialValue: "Do 260€",
    description: "Luxury lifestyle! Designer dodaci za žene.",
    includes: ["Designer item", "Jewelry", "Perfume", "Makeup", "Luxury treats"],
  },
  {
    id: "clothing-ysl-signature",
    name: "YSL Signature",
    slug: "ysl-signature",
    category: "clothing",
    price: 100,
    originalPrice: 260,
    image: "/images/01JDA537W5RZR5T0AK9HVNJCN7.webp",
    rating: 4.9,
    reviews: 445,
    stock: 11,
    potentialValue: "Do 500€",
    description: "Saint Laurent! YSL torbe, parfemi i fashion.",
    includes: ["YSL bag/perfume", "Accessories", "Makeup", "Scarf", "Luxury item"],
  },
  {
    id: "clothing-prada-privilege",
    name: "Prada Privilege Box",
    slug: "prada-privilege-box",
    category: "clothing",
    price: 75,
    originalPrice: 200,
    image: "/images/01JXMW9NMH2G4EZ6NRRX6XX8GB.webp",
    rating: 5.0,
    reviews: 356,
    stock: 13,
    potentialValue: "Do 420€",
    description: "Italian luxury! Prada torbe i high fashion dodaci.",
    includes: ["Prada accessory", "Wallet", "Keychain", "Sunglasses", "Premium item"],
  },
  {
    id: "clothing-top-g",
    name: "Top G Box",
    slug: "top-g-box",
    category: "clothing",
    price: 250,
    originalPrice: 600,
    image: "/images/01HQ0PEK0VJDDQEV5JHF9ZK1QD.webp",
    rating: 5.0,
    reviews: 189,
    stock: 4,
    potentialValue: "Do 1200€",
    description: "Alpha luxury! Premium designer komadi i dodaci.",
    includes: ["Luxury watch", "Designer clothing", "Accessories", "Grooming kit", "VIP items"],
  },
  {
    id: "clothing-50-50-burberry",
    name: "50-50 Burberry",
    slug: "50-50-burberry",
    category: "clothing",
    price: 300,
    originalPrice: 750,
    image: "/images/01JXMW8TM8REC53YQW908GA0FE.webp",
    rating: 5.0,
    reviews: 145,
    stock: 3,
    potentialValue: "Do 1500€",
    description: "50% šansa za Burberry! Legendrani trench ili dodaci.",
    includes: ["Burberry trench/scarf", "Accessories", "Bag", "Premium items", "Certificate"],
  },
  {
    id: "clothing-armani",
    name: "Armani Box",
    slug: "armani-box",
    category: "clothing",
    price: 75,
    originalPrice: 190,
    image: "/images/01JXMWE4X56P76BMCNE5PYPCKS.webp",
    rating: 4.9,
    reviews: 423,
    stock: 16,
    potentialValue: "Do 400€",
    description: "Italian elegance! Armani parfemi, odjeća i dodaci.",
    includes: ["Armani perfume", "Shirt/polo", "Belt", "Accessories", "Premium item"],
  },
  {
    id: "clothing-50-50-jacquemus",
    name: "50-50 Jacquemus Box",
    slug: "50-50-jacquemus-box",
    category: "clothing",
    price: 100,
    originalPrice: 270,
    image: "/images/01JPWBTHR4A3QRNVANP3TFFMS6.webp",
    rating: 4.9,
    reviews: 234,
    stock: 9,
    potentialValue: "Do 550€",
    description: "French fashion! 50% šansa za Jacquemus bag.",
    includes: ["Jacquemus bag/hat", "Accessories", "Sunglasses", "Clothing", "Premium item"],
  },
  {
    id: "clothing-after-party",
    name: "After Party Box",
    slug: "after-party-box",
    category: "clothing",
    price: 50,
    originalPrice: 130,
    image: "/images/01KD0T560GSX5TVB8BNMGZF3E2.webp",
    rating: 4.8,
    reviews: 567,
    stock: 24,
    potentialValue: "Do 240€",
    description: "Party outfit! Clubbing odjeća i dodaci.",
    includes: ["Party outfit", "Accessories", "Jewelry", "Makeup", "Club essentials"],
  },
  {
    id: "clothing-rich-kid",
    name: "Rich Kid",
    slug: "rich-kid",
    category: "clothing",
    price: 150,
    originalPrice: 400,
    image: "/images/01J1SGK9QBA3QPASE6MC7F74W2.webp",
    rating: 5.0,
    reviews: 278,
    stock: 7,
    potentialValue: "Do 800€",
    description: "Young luxury! Designer streetwear za mladu generaciju.",
    includes: ["Designer hoodie", "Sneakers", "Accessories", "Bag", "Premium items"],
  },
  {
    id: "clothing-lvmh",
    name: "LVMH Box",
    slug: "lvmh-box",
    category: "clothing",
    price: 100,
    originalPrice: 280,
    image: "/images/01J7644YSDDZ1RQQPM75241EBM.webp",
    rating: 5.0,
    reviews: 389,
    stock: 12,
    potentialValue: "Do 600€",
    description: "Luxury group! Louis Vuitton, Dior, Fendi komadi.",
    includes: ["LVMH brand item", "Accessories", "Perfume", "Bag/wallet", "Premium item"],
  },
  {
    id: "clothing-arcteryx",
    name: "Arcteryx Box",
    slug: "arcteryx-box",
    category: "clothing",
    price: 75,
    originalPrice: 200,
    image: "/images/01K2PHDP46XC8F62RAHK6WWH10.webp",
    rating: 4.9,
    reviews: 345,
    stock: 18,
    potentialValue: "Do 450€",
    description: "Technical fashion! Arc'teryx jakne i outdoor gear.",
    includes: ["Arc jacket/fleece", "Cap", "Backpack", "Accessories", "Tech wear"],
  },
  {
    id: "clothing-dior",
    name: "Dior Box",
    slug: "dior-box",
    category: "clothing",
    price: 100,
    originalPrice: 270,
    image: "/images/01HND8BPMYW94SK36CFHPFCMZS.webp",
    rating: 5.0,
    reviews: 567,
    stock: 10,
    potentialValue: "Do 550€",
    description: "French couture! Dior parfemi, makeup i fashion.",
    includes: ["Dior perfume", "Makeup", "Accessories", "Bag", "Luxury item"],
  },
  {
    id: "clothing-gucci-gang",
    name: "Gucci Gang Box",
    slug: "gucci-gang-box",
    category: "clothing",
    price: 75,
    originalPrice: 195,
    image: "/images/01HND926KKJF3V081HNE30BQ53.webp",
    rating: 4.9,
    reviews: 678,
    stock: 15,
    potentialValue: "Do 420€",
    description: "Italian fashion! Gucci dodaci i streetwear.",
    includes: ["Gucci accessory", "Belt", "Wallet", "Scarf", "Premium item"],
  },
  {
    id: "clothing-50-50-drip",
    name: "50-50 Drip Box",
    slug: "50-50-drip-box",
    category: "clothing",
    price: 50,
    originalPrice: 140,
    image: "/images/01HWYY4P7V5PHMCJXKMV8ZD719.webp",
    rating: 4.8,
    reviews: 890,
    stock: 26,
    potentialValue: "Do 300€",
    description: "50% za designer! Street fashion i brand dodaci.",
    includes: ["Designer item", "Accessories", "Jewelry", "Cap", "Surprise luxury"],
  },
  {
    id: "clothing-yeezy",
    name: "Yeezy Box",
    slug: "yeezy-box",
    category: "clothing",
    price: 50,
    originalPrice: 135,
    image: "/images/01JTX8NWEV8QBD7HQBFE7MN7P1.webp",
    rating: 4.9,
    reviews: 789,
    stock: 19,
    potentialValue: "Do 280€",
    description: "Kanye vision! Yeezy slides, foam runners i apparel.",
    includes: ["Yeezy slides/foam", "Hoodie", "Socks", "Cap", "Merch"],
  },
  {
    id: "clothing-supreme",
    name: "Supreme Box",
    slug: "supreme-box",
    category: "clothing",
    price: 100,
    originalPrice: 250,
    image: "/images/01HWD54B5YQ97SXKB2EACJMXTA.webp",
    rating: 5.0,
    reviews: 1234,
    stock: 14,
    potentialValue: "Do 500€",
    description: "Streetwear king! Supreme box logo i kolabs.",
    includes: ["Supreme tee/hoodie", "Accessories", "Stickers", "Bag", "Limited item"],
  },
  {
    id: "clothing-bape",
    name: "Bape Box",
    slug: "bape-box",
    category: "clothing",
    price: 50,
    originalPrice: 130,
    image: "/images/01HQJ8V6TJ2SNG34Q6KKXVVPAN.webp",
    rating: 4.8,
    reviews: 678,
    stock: 21,
    potentialValue: "Do 260€",
    description: "Japanese street! Bape camo, shark hoodie i dodaci.",
    includes: ["Bape tee", "Camo accessories", "Stickers", "Cap", "Merch"],
  },
  {
    id: "clothing-cp-company",
    name: "CP Company Box",
    slug: "cp-company-box",
    category: "clothing",
    price: 100,
    originalPrice: 260,
    image: "/images/01JTX8P4S0NFGNTTDEVP04H2N9.webp",
    rating: 4.9,
    reviews: 234,
    stock: 11,
    potentialValue: "Do 480€",
    description: "Italian sportswear! CP Company goggle jakne.",
    includes: ["CP jacket/shirt", "Accessories", "Cap", "Pants", "Premium item"],
  },
  {
    id: "clothing-detention",
    name: "Detention Box",
    slug: "detention-box",
    category: "clothing",
    price: 75,
    originalPrice: 180,
    image: "/images/01K51M3NWH8TRD1DQEJ9KKZY6Z.webp",
    rating: 4.7,
    reviews: 345,
    stock: 17,
    potentialValue: "Do 320€",
    description: "School vibes! Vintage college i prep odjeća.",
    includes: ["College hoodie", "Varsity jacket", "Backpack", "Cap", "Accessories"],
  },
  {
    id: "clothing-old-money",
    name: "Old Money Box",
    slug: "old-money-box",
    category: "clothing",
    price: 75,
    originalPrice: 190,
    image: "/images/01J0JRVPW77YPAVZ50D8EBG9PS.webp",
    rating: 5.0,
    reviews: 456,
    stock: 13,
    potentialValue: "Do 400€",
    description: "Classic elegance! Polo, chinos i timeless fashion.",
    includes: ["Polo shirt", "Chinos", "Leather belt", "Loafers", "Accessories"],
  },
  {
    id: "clothing-corteiz",
    name: "Corteiz Box",
    slug: "corteiz-box",
    category: "clothing",
    price: 50,
    originalPrice: 130,
    image: "/images/01JTX8PVCGDPZY2Z31REFC4787.webp",
    rating: 4.9,
    reviews: 789,
    stock: 20,
    potentialValue: "Do 250€",
    description: "UK streetwear! Corteiz hoodie i hype clothing.",
    includes: ["Corteiz hoodie/tee", "Cap", "Socks", "Stickers", "Limited merch"],
  },
  {
    id: "clothing-victorias-secret",
    name: "Victorias Secret Box",
    slug: "victorias-secret-box",
    category: "clothing",
    price: 75,
    originalPrice: 180,
    image: "/images/01JNRFA06SBTA738VNCB6XBWY1.webp",
    rating: 4.8,
    reviews: 1123,
    stock: 25,
    potentialValue: "Do 300€",
    description: "Beauty i lingerie! VS parfemi, odjeća i beauty.",
    includes: ["VS perfume", "Lingerie", "Lotion", "Bag", "Beauty products"],
  },
  {
    id: "clothing-adidas",
    name: "Adidas Box",
    slug: "adidas-box",
    category: "clothing",
    price: 50,
    originalPrice: 125,
    image: "/images/01K2PH4W6K47MJ0Z19BSA7CJPC.webp",
    rating: 4.7,
    reviews: 934,
    stock: 32,
    potentialValue: "Do 220€",
    description: "Three stripes! Adidas originals i sportswear.",
    includes: ["Adidas hoodie/tee", "Track pants", "Cap", "Socks", "Accessories"],
  },
    {
    id: "games-assassins-box",
    name: "Assassins Box",
    slug: "assassins-box",
    category: "games",
    price: 50,
    originalPrice: 139,
    image: "/images/01JH8811J8ZSQM9AX013JBACHJ.webp",
    rating: 4.8,
    reviews: 532,
    stock: 18,
    tag: "digital",
    potentialValue: "Do 200€",
    description: "Assassin's Creed kolekcija! Igre, merchandise i ekskluzivni kolekcionarski predmeti.",
    includes: ["AC igra", "Figura", "Poster", "Hoodie", "Hidden blade replika"],
  },
  {
    id: "games-gta-box",
    name: "GTA Box",
    slug: "gta-box",
    category: "games",
    price: 50,
    originalPrice: 135,
    image: "/images/01J8SMCKDQT4MEKWT6Y45304YB.webp",
    rating: 4.9,
    reviews: 1847,
    stock: 12,
    tag: "digital",
    potentialValue: "Do 250€",
    description: "Grand Theft Auto kolekcija! Vice City vibes s ekskluzivnim GTA sadržajem.",
    includes: ["GTA igra", "Kolekcionarska figura", "Poster set", "Keychain", "Stickers"],
  },
  {
    id: "games-yugioh-box",
    name: "Yu-Gi-Oh Box",
    slug: "yugioh-box",
    category: "card-games",
    price: 75,
    originalPrice: 189,
    image: "/images/01JT93TBB4Z93JQ4CE7HNZ1D2R.webp",
    rating: 4.9,
    reviews: 923,
    stock: 8,
    potentialValue: "Do 350€",
    description: "Duel! Yu-Gi-Oh premium kolekcija s rijetkim kartama i dodacima.",
    includes: ["Booster packs", "Holographic karte", "Playmat", "Deck box", "Sleeves"],
  },
  {
    id: "games-south-park-box",
    name: "South Park Box",
    slug: "south-park-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/01JPAJ00B9TB144FPJADRAY89V.webp",
    rating: 4.7,
    reviews: 456,
    stock: 22,
    potentialValue: "Do 180€",
    description: "South Park ludnica! Collector's edition s figurama i dodacima.",
    includes: ["Figurice", "Poster", "T-shirt", "Sticker pack", "DVD set"],
  },
  {
    id: "games-gangster-movies-box",
    name: "Gangster Movies Box",
    slug: "gangster-movies-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/01JWGM9R3RFJ9DWX0GKA8GR521.webp",
    rating: 4.8,
    reviews: 378,
    stock: 15,
    potentialValue: "Do 200€",
    description: "Mafija kolekcija! Godfather, Scarface i druge klasike.",
    includes: ["Blu-ray kolekcija", "Poster", "Replica props", "Art book", "Keychain"],
  },
  {
    id: "games-indiana-box",
    name: "Indiana Box",
    slug: "indiana-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/01JCQQMQHA48HKSCPJFJ4TPTDS.webp",
    rating: 4.6,
    reviews: 289,
    stock: 19,
    potentialValue: "Do 190€",
    description: "Indiana Jones avantura! Kolekcionarski predmeti i memorabilije.",
    includes: ["Replica whip", "Fedora hat", "Poster", "Action figura", "Prop replicas"],
  },
  {
    id: "games-mafia-box",
    name: "Mafia Box",
    slug: "mafia-box",
    category: "tv",
    price: 50,
    originalPrice: 139,
    image: "/images/01JGP0B3CCQTVZX5CVEB23DAQ6.webp",
    rating: 4.7,
    reviews: 412,
    stock: 14,
    potentialValue: "Do 210€",
    description: "Mafia trilogija! Gaming i kolekcionarski sadržaj.",
    includes: ["Mafia igra", "Art book", "Soundtrack", "Poster", "Vintage props"],
  },
  {
    id: "games-agent-007-box",
    name: "Agent 007 Box",
    slug: "agent-007-box",
    category: "tv",
    price: 50,
    originalPrice: 145,
    image: "/images/01JGP0C500HW5VRX8T73FDHH9E.webp",
    rating: 4.9,
    reviews: 634,
    stock: 11,
    potentialValue: "Do 240€",
    description: "James Bond kolekcija! Ekskluzivni 007 memorabilije.",
    includes: ["Blu-ray set", "Replica props", "Tuxedo pin", "Poster", "Martini glass"],
  },
  {
    id: "games-star-wars-box",
    name: "Star Wars Box",
    slug: "star-wars-box",
    category: "tv",
    price: 50,
    originalPrice: 139,
    image: "/images/01JQKG8VVJ6STZ481ZHN1SJPS1.webp",
    rating: 4.9,
    reviews: 1567,
    stock: 9,
    potentialValue: "Do 280€",
    description: "May the Force be with you! Ultimate Star Wars kolekcija.",
    includes: ["Lightsaber replica", "Black Series figura", "Poster", "Helmet replica", "Art book"],
  },
  {
    id: "games-marvel-box",
    name: "Marvel Box",
    slug: "marvel-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/01JGP0BRECKNRA8PTFSB2VRCJ9.webp",
    rating: 4.8,
    reviews: 1234,
    stock: 16,
    potentialValue: "Do 250€",
    description: "Marvel Cinematic Universe! Superhero kolekcija.",
    includes: ["Action figura", "Comic books", "Poster set", "Hoodie", "Props replicas"],
  },
  {
    id: "games-fast-furious-box",
    name: "Fast n Furious Box",
    slug: "fast-furious-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/01JCQQT8806E1VPNZD32H3VTXK.webp",
    rating: 4.7,
    reviews: 845,
    stock: 21,
    potentialValue: "Do 220€",
    description: "Fast & Furious adrenalin! Die-cast auta i filmski memorabilije.",
    includes: ["Die-cast model cars", "Poster", "Keychain", "Blu-ray", "T-shirt"],
  },
  {
    id: "games-futurama-box",
    name: "Futurama Box",
    slug: "futurama-box",
    category: "tv",
    price: 50,
    originalPrice: 125,
    image: "/images/01JPAHYS8CB9RR9TGAD5BQ6WZM.webp",
    rating: 4.6,
    reviews: 367,
    stock: 27,
    potentialValue: "Do 170€",
    description: "Good news everyone! Futurama kolekcionarska kolekcija.",
    includes: ["Figurice", "DVD set", "Poster", "T-shirt", "Collectibles"],
  },
  {
    id: "games-dragon-ball-z-box",
    name: "Dragon Ball Z Box",
    slug: "dragon-ball-z-box",
    category: "tv",
    price: 50,
    originalPrice: 139,
    image: "/images/01JAFXPGZ8XWHQDW1Y8VWQFV5R.webp",
    rating: 4.9,
    reviews: 2134,
    stock: 7,
    potentialValue: "Do 270€",
    description: "Over 9000! DBZ ultimate kolekcija s figurama i igrama.",
    includes: ["Action figura", "Trading cards", "Poster", "Gaming controller skin", "Manga"],
  },
  {
    id: "games-breaking-bad-box",
    name: "Breaking Bad Box",
    slug: "breaking-bad-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/01JGP0A0FVNG29AEEMSD8NAFD0.webp",
    rating: 4.9,
    reviews: 987,
    stock: 13,
    potentialValue: "Do 240€",
    description: "I am the one who knocks! Breaking Bad collector's edition.",
    includes: ["Blu-ray box set", "RV model", "Poster", "Props replicas", "Art book"],
  },
  {
    id: "games-jurassic-box",
    name: "Jurassic Box",
    slug: "jurassic-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/01JCQR9GQWFNN5CSSHNK877H6Q.webp",
    rating: 4.7,
    reviews: 678,
    stock: 18,
    potentialValue: "Do 200€",
    description: "Jurassic Park nostalgia! Dinosaur kolekcija i filmski dodaci.",
    includes: ["Dinosaur figurice", "Jeep model", "Poster", "Blu-ray", "Props"],
  },
  {
    id: "games-rick-morty-box",
    name: "Rick and Morty Box",
    slug: "rick-morty-box",
    category: "tv",
    price: 50,
    originalPrice: 139,
    image: "/images/01JPAHXZR4NEZJ2H6TE9AEMQ1E.webp",
    rating: 4.8,
    reviews: 1456,
    stock: 10,
    potentialValue: "Do 230€",
    description: "Wubba lubba dub dub! Rick and Morty interdimensional box.",
    includes: ["Figurice", "Portal gun replica", "Poster", "T-shirt", "Stickers"],
  },
  {
    id: "games-one-piece-box",
    name: "One Piece Box",
    slug: "one-piece-box",
    category: "tv",
    price: 50,
    originalPrice: 145,
    image: "/images/01JAFXNJ3WZ4RA2A3QKHAPHCZT.webp",
    rating: 4.9,
    reviews: 1789,
    stock: 8,
    potentialValue: "Do 280€",
    description: "Pirate King kolekcija! One Piece ultimate treasure box.",
    includes: ["Action figura", "Trading cards", "Manga", "Poster", "Straw hat replica"],
  },
  {
    id: "games-simpsons-box",
    name: "Simpsons Box",
    slug: "simpsons-box",
    category: "tv",
    price: 50,
    originalPrice: 125,
    image: "/images/01JPAHX0V21Q97XS14DP7G50RY.webp",
    rating: 4.7,
    reviews: 823,
    stock: 25,
    potentialValue: "Do 190€",
    description: "D'oh! Simpsons kolekcionarska kutija s retro dodacima.",
    includes: ["Figurice", "DVD set", "Poster", "Duff beer glass", "Collectibles"],
  },
  {
    id: "games-casa-papel-box",
    name: "Casa De Papel Box",
    slug: "casa-papel-box",
    category: "tv",
    price: 50,
    originalPrice: 139,
    image: "/images/01JQKG88TSZ93GN9XH35ZNHFYW.webp",
    rating: 4.8,
    reviews: 1123,
    stock: 12,
    potentialValue: "Do 230€",
    description: "Bella Ciao! Money Heist kolekcionarska kolekcija.",
    includes: ["Dali maska", "Red jumpsuit", "Poster", "Props replicas", "Art book"],
  },
  {
    id: "games-back-future-box",
    name: "Back To Future Box",
    slug: "back-future-box",
    category: "tv",
    price: 50,
    originalPrice: 145,
    image: "/images/01JCQRTV61Q9M8M8VD9E0PWS9K.webp",
    rating: 4.9,
    reviews: 756,
    stock: 14,
    potentialValue: "Do 260€",
    description: "Great Scott! Back to the Future kolekcija.",
    includes: ["DeLorean model", "Hoverboard replica", "Poster", "Blu-ray", "Clock tower prop"],
  },
  {
    id: "games-naruto-box",
    name: "Naruto Box",
    slug: "naruto-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/01JAFXRAVH2PTWENFSQ90513AA.webp",
    rating: 4.9,
    reviews: 2345,
    stock: 6,
    potentialValue: "Do 270€",
    description: "Believe it! Naruto Shippuden ultimate ninja box.",
    includes: ["Action figura", "Headband", "Trading cards", "Manga", "Kunai replica"],
  },
  {
    id: "games-attack-titan-box",
    name: "Attack On Titan Box",
    slug: "attack-titan-box",
    category: "tv",
    price: 50,
    originalPrice: 139,
    image: "/images/01JAFXTAMZM5BWF406MR35RAKQ.webp",
    rating: 4.8,
    reviews: 1567,
    stock: 9,
    potentialValue: "Do 250€",
    description: "Shinzou wo Sasageyo! Attack on Titan kolekcionarska kutija.",
    includes: ["Survey Corps figura", "Maneuver gear keychain", "Manga", "Poster", "Scouting cloak"],
  },
  {
    id: "games-death-note-box",
    name: "Death Note Box",
    slug: "death-note-box",
    category: "tv",
    price: 50,
    originalPrice: 129,
    image: "/images/01JAFXV9K838BDNQWQSG35G745 (2).webp",
    rating: 4.7,
    reviews: 945,
    stock: 17,
    potentialValue: "Do 210€",
    description: "Kira's legacy! Death Note kolekcionarska kolekcija.",
    includes: ["Death Note replica", "Ryuk figura", "Manga set", "Poster", "L keychain"],
  },
  {
    id: "games-squid-game-box",
    name: "Squid Game Box",
    slug: "squid-game-box",
    category: "tv",
    price: 50,
    originalPrice: 135,
    image: "/images/01JQKG80JSFM31ZDS9FHG44WM0.webp",
    rating: 4.9,
    reviews: 1678,
    stock: 11,
    potentialValue: "Do 240€",
    description: "Red light, green light! Squid Game survival kit.",
    includes: ["Player tracksuit", "Guard mask", "Dalgona cookie mold", "Poster", "Playing cards"],
  },
  {
    id: "games-harry-potter-box",
    name: "Harry Potter Box",
    slug: "harry-potter-box",
    category: "tv",
    price: 50,
    originalPrice: 145,
    image: "/images/01JQKG7PSW9BRVEDCG9ZASQK22.webp",
    rating: 4.9,
    reviews: 2456,
    stock: 5,
    potentialValue: "Do 290€",
    description: "Magical mystery! Harry Potter wizard's collection.",
    includes: ["Wand replica", "House scarf", "Marauder's Map", "Chocolate frog", "Blu-ray set"],
  },
  {
    id: "games-pokemon-insane-box",
    name: "Pokemon INSANE Box",
    slug: "pokemon-insane-box",
    category: "card-games",
    price: 250,
    originalPrice: 599,
    image: "/images/01HS4KYNEHXY82Y39MANK851HW.webp",
    rating: 5.0,
    reviews: 234,
    stock: 3,
    potentialValue: "Do 1500€",
    description: "ULTRA RARE! Pokemon kolekcija s holographic i vintage kartama.",
    includes: ["Graded PSA karte", "Elite Trainer Box", "Booster boxes", "Vintage packs", "Charizard šansa"],
  },
  {
    id: "games-pokemon-ultra-box",
    name: "Pokemon Ultra Box",
    slug: "pokemon-ultra-box",
    category: "card-games",
    price: 85,
    originalPrice: 219,
    image: "/images/01K4CXHWCZD975G9KD1SC0MNA4.webp",
    rating: 4.9,
    reviews: 1234,
    stock: 8,
    potentialValue: "Do 400€",
    description: "Premium Pokemon kolekcija s rijetkim booster packovima.",
    includes: ["Booster box", "Elite trainer box", "Promo cards", "Sleeves", "Playmat"],
  },
  {
    id: "games-pokemon-booster-box",
    name: "Pokemon Booster Box",
    slug: "pokemon-booster-box",
    category: "card-games",
    price: 35,
    originalPrice: 89,
    image: "/images/01K4CXHJEQ2XTYM2NW7A1HTAKV.webp",
    rating: 4.7,
    reviews: 2345,
    stock: 45,
    potentialValue: "Do 150€",
    description: "Pokemon booster pack bonanza! Novi setovi i promo karte.",
    includes: ["Booster packs", "Promo card", "Coin", "Stickers", "Code cards"],
  },
  {
    id: "games-pokemon-deluxe-box",
    name: "Pokemon Deluxe Box",
    slug: "pokemon-deluxe-box",
    category: "card-games",
    price: 50,
    originalPrice: 129,
    image: "/images/01HS4M2XHNSV6PQP343MG7JQ35.webp",
    rating: 4.8,
    reviews: 1567,
    stock: 23,
    potentialValue: "Do 220€",
    description: "Deluxe Pokemon paket! Trading cards i gaming dodaci.",
    includes: ["Elite trainer box", "Tin box", "Sleeves", "Playmat", "Dice set"],
  },
  {
    id: "games-mtg-box",
    name: "MTG: Magic The Gathering Box",
    slug: "mtg-box",
    category: "card-games",
    price: 35,
    originalPrice: 89,
    image: "/images/01JT9401CZTN5WKXRW53XKF311 (1).webp",
    rating: 4.8,
    reviews: 876,
    stock: 34,
    potentialValue: "Do 180€",
    description: "Summon the cards! Magic: The Gathering kolekcija.",
    includes: ["Booster packs", "Commander deck", "Rare cards", "Playmat", "Sleeves"],
  },
  {
    id: "games-mortal-kombat-box",
    name: "Mortal Kombat Box",
    slug: "mortal-kombat-box",
    category: "games",
    price: 35,
    originalPrice: 95,
    image: "/images/01JVC75V6VBDYSX5VDZSEA9GQV.webp",
    rating: 4.7,
    reviews: 645,
    stock: 28,
    tag: "digital",
    potentialValue: "Do 160€",
    description: "FINISH HIM! Mortal Kombat fatality collection.",
    includes: ["MK igra", "Action figura", "Poster", "Controller skin", "Props"],
  },
  {
    id: "games-far-cry-box",
    name: "Far Cry Box",
    slug: "far-cry-box",
    category: "games",
    price: 35,
    originalPrice: 89,
    image: "/images/01JVC75XS13N1PEM2BGNSQAPPF.webp",
    rating: 4.6,
    reviews: 423,
    stock: 32,
    tag: "digital",
    potentialValue: "Do 150€",
    description: "Island survival! Far Cry jungle kolekcija.",
    includes: ["Far Cry igra", "Survival gear", "Poster", "Art book", "Props"],
  },
  {
    id: "games-random-horror-box",
    name: "Random Horror Box",
    slug: "random-horror-box",
    category: "games",
    price: 35,
    originalPrice: 95,
    image: "/images/01JAZFWCVFNR7B8F4HB9F3RJPH.webp",
    rating: 4.8,
    reviews: 789,
    stock: 19,
    tag: "digital",
    potentialValue: "Do 170€",
    description: "Scream! Horror gaming i film memorabilije.",
    includes: ["Horror igra", "Mask replica", "Poster", "Collectibles", "Props"],
  },
  {
    id: "games-cod-box",
    name: "COD Box",
    slug: "cod-box",
    category: "games",
    price: 35,
    originalPrice: 89,
    image: "/images/01J8SMBYCQ2FWA9XRJ9KS89J6E.webp",
    rating: 4.7,
    reviews: 1345,
    stock: 41,
    tag: "digital",
    potentialValue: "Do 160€",
    description: "Call of Duty warfare! COD gaming paket.",
    includes: ["COD igra", "Controller skin", "Poster", "Keychain", "Stickers"],
  },
  {
    id: "games-witcher-box",
    name: "Witcher Box",
    slug: "witcher-box",
    category: "games",
    price: 35,
    originalPrice: 95,
    image: "/images/01K9EPTFWK8BJ56RKZ1C3P5K8J.webp",
    rating: 4.9,
    reviews: 1678,
    stock: 15,
    tag: "digital",
    potentialValue: "Do 190€",
    description: "Toss a coin! Witcher 3 kolekcionarska kolekcija.",
    includes: ["Witcher 3 igra", "Medallion replica", "Poster", "Art book", "Gwent cards"],
  },
  {
    id: "games-roblox-box",
    name: "Roblox Box",
    slug: "roblox-box",
    category: "games",
    price: 35,
    originalPrice: 85,
    image: "/images/01J8SMDAE4RYD8D8QWZXZW82HG.webp",
    rating: 4.6,
    reviews: 2134,
    stock: 56,
    tag: "digital",
    potentialValue: "Do 140€",
    description: "Oof! Roblox gaming i figurice kolekcija.",
    includes: ["Robux gift card", "Figurice", "Stickers", "Poster", "Codes"],
  },
  {
    id: "games-minecraft-box",
    name: "Minecraft Box",
    slug: "minecraft-box",
    category: "games",
    price: 35,
    originalPrice: 89,
    image: "/images/01J8SMDNX9097AC7Y9P7N037TR.webp",
    rating: 4.8,
    reviews: 3456,
    stock: 67,
    tag: "digital",
    potentialValue: "Do 160€",
    description: "Dig it! Minecraft builders paradise box.",
    includes: ["Minecraft account", "Lego sets", "Figurice", "Poster", "Pickaxe replica"],
  },
  {
    id: "games-fortnite-box",
    name: "Fortnite Box",
    slug: "fortnite-box",
    category: "games",
    price: 35,
    originalPrice: 89,
    image: "/images/01J8SMAMYV9NV6ZJCGBPQT939H.webp",
    rating: 4.7,
    reviews: 2789,
    stock: 43,
    tag: "digital",
    potentialValue: "Do 170€",
    description: "Victory Royale! Fortnite V-Bucks i gaming gear.",
    includes: ["V-Bucks card", "Figurice", "Controller skin", "Poster", "Backpack keychain"],
  },
  {
    id: "games-tomb-raider-box",
    name: "Tomb Raider Box",
    slug: "tomb-raider-box",
    category: "games",
    price: 35,
    originalPrice: 95,
    image: "/images/01K9EPTDSN2AA21GYV3MQ8D04Z.webp",
    rating: 4.6,
    reviews: 456,
    stock: 29,
    tag: "digital",
    potentialValue: "Do 160€",
    description: "Lara Croft adventure! Tomb Raider collectors edition.",
    includes: ["Tomb Raider igra", "Lara figura", "Poster", "Props replicas", "Art book"],
  },
  {
    id: "games-rust-raid-box",
    name: "Rust Raid Box",
    slug: "rust-raid-box",
    category: "games",
    price: 35,
    originalPrice: 89,
    image: "/images/01JJXQ60EWF4YV5EWKRYZ0Z4S3.webp",
    rating: 4.5,
    reviews: 234,
    stock: 38,
    tag: "digital",
    potentialValue: "Do 150€",
    description: "Survival mode! Rust gaming paket.",
    includes: ["Rust Steam key", "Gaming gear", "Poster", "Stickers", "Props"],
  },
  {
    id: "games-batman-dark-box",
    name: "Batman Dark Box",
    slug: "batman-dark-box",
    category: "games",
    price: 35,
    originalPrice: 95,
    image: "/images/01JVC75123KXDARFMS0ABM81H6.webp",
    rating: 4.9,
    reviews: 1234,
    stock: 21,
    tag: "digital",
    potentialValue: "Do 200€",
    description: "I am vengeance! Batman Arkham kolekcionarska kutija.",
    includes: ["Arkham igra", "Batarang replica", "Mask", "Poster", "Collectibles"],
  },
  {
    id: "games-cs2-skin-special-box",
    name: "CS2 Skin Special Box",
    slug: "cs2-skin-special-box",
    category: "games",
    price: 35,
    originalPrice: 95,
    image: "/images/01JJXQ6ZWQCTC5HQZ6BJN9BXXS.webp",
    rating: 4.8,
    reviews: 1567,
    stock: 26,
    tag: "digital",
    potentialValue: "Do 180€",
    description: "Rush B! CS2 skin kolekcija i gaming oprema.",
    includes: ["CS2 skins code", "Gaming mousepad", "Stickers", "Poster", "Keychain"],
  },
   {
    id: "Camera Box",
    name: "Camera Box",
    slug: "Camera Box",
    category: "tech",
    price: 75,
    originalPrice: 99,
    image: "/images/01KAK6HDAJMYFFKBYGRW70434B.webp",
    rating: 4.7,
    reviews: 445,
    stock: 34,
    potentialValue: "Do 200€",
    description: "Skate or die! Skate cipele i accessories.",
    includes: ["Skate shoes", "Extra laces", "Shoe goo", "Skate socks", "Accessories"],
  },
    {
    id: "Tech Enthusiast Box",
    name: "Tech Enthusiast Box",
    slug: "Tech Enthusiast Box",
    category: "tech",
    price: 150,
    originalPrice: 99,
    image: "/images/01HNCVKY8SGM1CTY9VMPY3FGBW.webp",
    rating: 4.7,
    reviews: 445,
    stock: 34,
    potentialValue: "Do 200€",
    description: "Skate or die! Skate cipele i accessories.",
    includes: ["Skate shoes", "Extra laces", "Shoe goo", "Skate socks", "Accessories"],
  },
    {
    id: "Sky Signal Box",
    name: "Sky Signal Box",
    slug: "Sky Signal Box",
    category: "tech",
    price: 50,
    originalPrice: 99,
    image: "/images/01JHT9QK6Z7C2QQTBV270ZQRYS.webp",
    rating: 4.7,
    reviews: 445,
    stock: 34,
    potentialValue: "Do 200€",
    description: "Skate or die! Skate cipele i accessories.",
    includes: ["Skate shoes", "Extra laces", "Shoe goo", "Skate socks", "Accessories"],
  },
    {
    id: "Music Party Box ",
    name: "Music Party Box ",
    slug: "Music Party Box ",
    category: "tech",
    price: 50,
    originalPrice: 99,
    image: "/images/01JMM9AR74BT16E8HY2ERTT2EB.webp",
    rating: 4.7,
    reviews: 445,
    stock: 34,
    potentialValue: "Do 200€",
    description: "Skate or die! Skate cipele i accessories.",
    includes: ["Skate shoes", "Extra laces", "Shoe goo", "Skate socks", "Accessories"],
  },
    {
    id: "Nerd tech Box",
    name: "Nerd tech Box",
    slug: "Nerd tech Box",
    category: "tech",
    price: 50,
    originalPrice: 99,
    image: "/images/01JVY8EJRQ2BSXPCS08YGWB44M.webp",
    rating: 4.7,
    reviews: 445,
    stock: 34,
    potentialValue: "Do 200€",
    description: "Skate or die! Skate cipele i accessories.",
    includes: ["Skate shoes", "Extra laces", "Shoe goo", "Skate socks", "Accessories"],
  },
  {
    id: "RGB Gaming Box ",
    name: "RGB Gaming Box ",
    slug: "RGB Gaming Box ",
    category: "gaming",
    price: 50,
    originalPrice: 119,
    image: "/images/01HNCX10NCRKDWYFK4C61P7K95.webp",
    rating: 4.8,
    reviews: 1345,
    stock: 26,
    potentialValue: "Do 300€",
    description: "Za prave footballere! Dresovi, lopte i nogometna oprema.",
    includes: ["Dres tima", "Nogometna lopta", "Štucne", "Navijački šal", "Autographed item"],
  },
   {
    id: "Nintendo Box",
    name: "Nintendo Box",
    slug: "Nintendo Box ",
    category: "gaming",
    price: 75,
    originalPrice: 119,
    image: "/images/01HNCWZ298QB3ZY9530KQVT7AG.webp",
    rating: 4.8,
    reviews: 1345,
    stock: 26,
    potentialValue: "Do 300€",
    description: "Za prave footballere! Dresovi, lopte i nogometna oprema.",
    includes: ["Dres tima", "Nogometna lopta", "Štucne", "Navijački šal", "Autographed item"],
  },
   {
    id: "XBOX VS PS Box",
    name: "XBOX VS PS Box",
    slug: "XBOX VS PS Box",
    category: "gaming",
    price: 90,
    originalPrice: 119,
    image: "/images/01HPGY48ZYK7SEKYTBHRP7VMAP.webp",
    rating: 4.8,
    reviews: 1345,
    stock: 26,
    potentialValue: "Do 300€",
    description: "Za prave footballere! Dresovi, lopte i nogometna oprema.",
    includes: ["Dres tima", "Nogometna lopta", "Štucne", "Navijački šal", "Autographed item"],
  },
   {
    id: "Pro Gamer Box",
    name: "Pro Gamer Box",
    slug: "Pro Gamer Box",
    category: "gaming",
    price: 100,
    originalPrice: 119,
    image: "/images/01HPGY6BWRE8HW3WTE2MEJTAJZ.webp",
    rating: 4.8,
    reviews: 1345,
    stock: 26,
    potentialValue: "Do 300€",
    description: "Za prave footballere! Dresovi, lopte i nogometna oprema.",
    includes: ["Dres tima", "Nogometna lopta", "Štucne", "Navijački šal", "Autographed item"],
  },
   {
    id: "Streamer Box",
    name: "Streamer Box",
    slug: "Streamer Box",
    category: "gaming",
    price: 50,
    originalPrice: 119,
    image: "/images/01JDSHZZVRGKK7F8PH9C8VGSCF.webp",
    rating: 4.8,
    reviews: 1345,
    stock: 26,
    potentialValue: "Do 300€",
    description: "Za prave footballere! Dresovi, lopte i nogometna oprema.",
    includes: ["Dres tima", "Nogometna lopta", "Štucne", "Navijački šal", "Autographed item"],
  },
  {
    id: "Rich Gamer Box ",
    name: "Rich Gamer Box ",
    slug: "Rich Gamer Box ",
    category: "gaming",
    price: 150,
    originalPrice: 119,
    image: "/images/01K5GSNBV7C09T6XWCGAM70DYC.webp",
    rating: 4.8,
    reviews: 1345,
    stock: 26,
    potentialValue: "Do 300€",
    description: "Za prave footballere! Dresovi, lopte i nogometna oprema.",
    includes: ["Dres tima", "Nogometna lopta", "Štucne", "Navijački šal", "Autographed item"],
  },
    {
    id: "Gaming Empire Box",
    name: "Gaming Empire Box",
    slug: "Gaming Empire Box",
    category: "gaming",
    price: 200,
    originalPrice: 119,
    image: "/images/01HY13QBBT2AYF1J1NBTH3MH7C.webp",
    rating: 4.8,
    reviews: 1345,
    stock: 26,
    potentialValue: "Do 300€",
    description: "Za prave footballere! Dresovi, lopte i nogometna oprema.",
    includes: ["Dres tima", "Nogometna lopta", "Štucne", "Navijački šal", "Autographed item"],
  },
]

export function getProductsByCategory(categoryId: string) {
  return products.filter((p) => p.category === categoryId)
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug || p.id === slug)
}

export function getCategoryById(categoryId: string) {
  return categories.find((c) => c.id === categoryId)
}
